export type Region = {
  id: string;
  name: string;
  shortLabel: string;
  number: number;
  emoji: string;
  theme: string;
  cultureNote: string;
  accentColor: string;
};

export type GrammaticalGender = "masculine" | "feminine";

export type PartOfSpeech =
  | "noun"
  | "verb"
  | "pronominal verb"
  | "adjective";

export type Word = {
  id: string;
  regionId: Region["id"];
  french: string;
  search: string;
  english: string;
  ipa: string;
  partOfSpeech: PartOfSpeech;
  gender: GrammaticalGender | null;
  emoji: string;
  exampleFr: string;
  exampleEn: string;
};

export const REGIONS = [
  {
    id: "ile-de-france",
    name: "Île-de-France",
    shortLabel: "Paris",
    number: 1,
    emoji: "🏙️",
    theme: "City rhythm and culture",
    cultureNote:
      "Museums, neighbourhood cafés and a vast rail network make the capital region ideal for practical city French.",
    accentColor: "#315C8C",
  },
  {
    id: "hauts-de-france",
    name: "Hauts-de-France",
    shortLabel: "The North",
    number: 2,
    emoji: "🔔",
    theme: "Markets and warm welcomes",
    cultureNote:
      "The region is known for its beffries, festive street markets and a strong tradition of hospitality.",
    accentColor: "#2E7180",
  },
  {
    id: "normandie",
    name: "Normandie",
    shortLabel: "Normandy",
    number: 3,
    emoji: "🌊",
    theme: "Cliffs, tides and orchards",
    cultureNote:
      "Dramatic coastal scenery, dairy farms and apple orchards shape Normandy's everyday vocabulary.",
    accentColor: "#56658F",
  },
  {
    id: "bretagne",
    name: "Bretagne",
    shortLabel: "Brittany",
    number: 4,
    emoji: "⚓",
    theme: "Sea roads and crêpes",
    cultureNote:
      "Brittany's lighthouses, coastal paths and maritime traditions invite learners to speak about the sea.",
    accentColor: "#2E4C5C",
  },
  {
    id: "pays-de-la-loire",
    name: "Pays de la Loire",
    shortLabel: "Atlantic Loire",
    number: 5,
    emoji: "⛵",
    theme: "Estuary and wetlands",
    cultureNote:
      "Where the Loire reaches the Atlantic, estuary towns, marshes and sailing shape life near the water.",
    accentColor: "#2D7A6E",
  },
  {
    id: "centre-val-de-loire",
    name: "Centre-Val de Loire",
    shortLabel: "Loire Valley",
    number: 6,
    emoji: "🏰",
    theme: "Castles and gardens",
    cultureNote:
      "Renaissance châteaux and carefully designed gardens tell the story of France's royal valley.",
    accentColor: "#557A3A",
  },
  {
    id: "grand-est",
    name: "Grand Est",
    shortLabel: "Grand Est",
    number: 7,
    emoji: "🎄",
    theme: "Festivals and borderlands",
    cultureNote:
      "Cathedral cities, Christmas markets and cross-border traditions give the region a distinctive character.",
    accentColor: "#7B4B73",
  },
  {
    id: "bourgogne-franche-comte",
    name: "Bourgogne-Franche-Comté",
    shortLabel: "Burgundy",
    number: 8,
    emoji: "🍇",
    theme: "Vineyards and craft",
    cultureNote:
      "Vineyards, cellars, cheeses and wooded hills make this a rich region for food and landscape vocabulary.",
    accentColor: "#7A5236",
  },
  {
    id: "nouvelle-aquitaine",
    name: "Nouvelle-Aquitaine",
    shortLabel: "Aquitaine",
    number: 9,
    emoji: "🏄",
    theme: "Ocean and wide horizons",
    cultureNote:
      "Atlantic beaches, oyster beds, dunes and vineyards stretch across France's largest metropolitan region.",
    accentColor: "#2D718C",
  },
  {
    id: "auvergne-rhone-alpes",
    name: "Auvergne-Rhône-Alpes",
    shortLabel: "Alps and Auvergne",
    number: 10,
    emoji: "🏔️",
    theme: "Volcanoes and high trails",
    cultureNote:
      "Ancient volcanoes meet Alpine summits in a region made for mountain, weather and hiking vocabulary.",
    accentColor: "#5F5B8C",
  },
  {
    id: "occitanie",
    name: "Occitanie",
    shortLabel: "Occitanie",
    number: 11,
    emoji: "🧱",
    theme: "Canals and sunlit squares",
    cultureNote:
      "Pink-brick cities, the Canal du Midi and lively public squares encourage a slower southern rhythm.",
    accentColor: "#B85C46",
  },
  {
    id: "provence-alpes-cote-d-azur",
    name: "Provence-Alpes-Côte d'Azur",
    shortLabel: "Provence",
    number: 12,
    emoji: "🪻",
    theme: "Lavender and Mediterranean coves",
    cultureNote:
      "Provençal markets, limestone calanques and lavender fields bring scent, colour and outdoor life together.",
    accentColor: "#C77C2E",
  },
  {
    id: "corse",
    name: "Corse",
    shortLabel: "Corsica",
    number: 13,
    emoji: "🏝️",
    theme: "Island paths and wild coast",
    cultureNote:
      "Mountain villages, fragrant maquis and a rugged coastline give Corsica its strong island identity.",
    accentColor: "#8A4F4A",
  },
  {
    id: "guadeloupe",
    name: "Guadeloupe",
    shortLabel: "Guadeloupe",
    number: 14,
    emoji: "🦋",
    theme: "Archipelago and Creole culture",
    cultureNote:
      "This Caribbean archipelago brings together rainforest, mangroves, lively markets and a rich French and Creole culture.",
    accentColor: "#2F806F",
  },
  {
    id: "martinique",
    name: "Martinique",
    shortLabel: "Martinique",
    number: 15,
    emoji: "⛵",
    theme: "Volcanic shores and flower gardens",
    cultureNote:
      "Traditional yoles, tropical gardens and the slopes of Mount Pelée shape everyday life on this Caribbean island.",
    accentColor: "#A35C43",
  },
  {
    id: "guyane",
    name: "Guyane",
    shortLabel: "French Guiana",
    number: 16,
    emoji: "🚀",
    theme: "Rainforest, rivers and space",
    cultureNote:
      "Amazonian forest and great rivers surround diverse towns, while rockets launch from the Guiana Space Centre near Kourou.",
    accentColor: "#397449",
  },
  {
    id: "la-reunion",
    name: "La Réunion",
    shortLabel: "Réunion",
    number: 17,
    emoji: "🌋",
    theme: "Cirques, peaks and a living volcano",
    cultureNote:
      "Mountain cirques, waterfalls and Piton de la Fournaise meet a vibrant French and Réunion Creole culture in the Indian Ocean.",
    accentColor: "#92523B",
  },
  {
    id: "mayotte",
    name: "Mayotte",
    shortLabel: "Mayotte",
    number: 18,
    emoji: "🐢",
    theme: "Lagoon and island life",
    cultureNote:
      "A vast Indian Ocean lagoon, coral reefs and mangroves support sea turtles and a deeply multilingual island culture.",
    accentColor: "#267C8A",
  },
] as const satisfies readonly Region[];

export const WORDS = [
  // Île-de-France
  {
    id: "idf-metro",
    regionId: "ile-de-france",
    french: "le métro",
    search: "metro",
    english: "the metro / subway",
    ipa: "/lə metʁo/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🚇",
    exampleFr: "Le métro passe toutes les trois minutes.",
    exampleEn: "The metro comes every three minutes.",
  },
  {
    id: "idf-musee",
    regionId: "ile-de-france",
    french: "un musée",
    search: "musee",
    english: "a museum",
    ipa: "/œ̃ myze/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🖼️",
    exampleFr: "Nous visitons un musée après le déjeuner.",
    exampleEn: "We are visiting a museum after lunch.",
  },
  {
    id: "idf-banlieue",
    regionId: "ile-de-france",
    french: "la banlieue",
    search: "banlieue",
    english: "the suburbs",
    ipa: "/la bɑ̃ljø/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🏘️",
    exampleFr: "Elle habite en banlieue et travaille à Paris.",
    exampleEn: "She lives in the suburbs and works in Paris.",
  },
  {
    id: "idf-se-depecher",
    regionId: "ile-de-france",
    french: "se dépêcher",
    search: "se depecher",
    english: "to hurry",
    ipa: "/sə depeʃe/",
    partOfSpeech: "pronominal verb",
    gender: null,
    emoji: "⏱️",
    exampleFr: "Il faut se dépêcher pour ne pas rater le train.",
    exampleEn: "We have to hurry so we do not miss the train.",
  },
  {
    id: "idf-anime",
    regionId: "ile-de-france",
    french: "animé",
    search: "anime",
    english: "lively / bustling",
    ipa: "/anime/",
    partOfSpeech: "adjective",
    gender: null,
    emoji: "✨",
    exampleFr: "Le quartier est animé le vendredi soir.",
    exampleEn: "The neighbourhood is lively on Friday evening.",
  },

  // Hauts-de-France
  {
    id: "hdf-braderie",
    regionId: "hauts-de-france",
    french: "la braderie",
    search: "braderie",
    english: "the street market / clearance sale",
    ipa: "/la bʁadʁi/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🛍️",
    exampleFr: "La braderie remplit les rues de stands colorés.",
    exampleEn: "The street market fills the streets with colourful stalls.",
  },
  {
    id: "hdf-beffroi",
    regionId: "hauts-de-france",
    french: "un beffroi",
    search: "beffroi",
    english: "a belfry",
    ipa: "/œ̃ befʁwa/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🔔",
    exampleFr: "Le beffroi domine la place centrale.",
    exampleEn: "The belfry overlooks the central square.",
  },
  {
    id: "hdf-gaufre",
    regionId: "hauts-de-france",
    french: "une gaufre",
    search: "gaufre",
    english: "a waffle",
    ipa: "/yn ɡofʁ/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🧇",
    exampleFr: "La gaufre est encore chaude.",
    exampleEn: "The waffle is still warm.",
  },
  {
    id: "hdf-chaleureux",
    regionId: "hauts-de-france",
    french: "chaleureux",
    search: "chaleureux",
    english: "warm / welcoming",
    ipa: "/ʃaløʁø/",
    partOfSpeech: "adjective",
    gender: null,
    emoji: "🤗",
    exampleFr: "Les habitants nous réservent un accueil chaleureux.",
    exampleEn: "The residents give us a warm welcome.",
  },
  {
    id: "hdf-accueillir",
    regionId: "hauts-de-france",
    french: "accueillir",
    search: "accueillir",
    english: "to welcome",
    ipa: "/akœjiʁ/",
    partOfSpeech: "verb",
    gender: null,
    emoji: "👋",
    exampleFr: "Le serveur nous accueille avec le sourire.",
    exampleEn: "The waiter welcomes us with a smile.",
  },

  // Normandie
  {
    id: "nor-falaise",
    regionId: "normandie",
    french: "une falaise",
    search: "falaise",
    english: "a cliff",
    ipa: "/yn falɛz/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🪨",
    exampleFr: "La falaise domine la mer.",
    exampleEn: "The cliff overlooks the sea.",
  },
  {
    id: "nor-cidre",
    regionId: "normandie",
    french: "le cidre",
    search: "cidre",
    english: "cider",
    ipa: "/lə sidʁ/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🍎",
    exampleFr: "Le cidre normand accompagne le repas.",
    exampleEn: "Norman cider accompanies the meal.",
  },
  {
    id: "nor-maree",
    regionId: "normandie",
    french: "la marée",
    search: "maree",
    english: "the tide",
    ipa: "/la maʁe/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🌊",
    exampleFr: "La marée monte rapidement ce soir.",
    exampleEn: "The tide is rising quickly this evening.",
  },
  {
    id: "nor-brumeux",
    regionId: "normandie",
    french: "brumeux",
    search: "brumeux",
    english: "misty / foggy",
    ipa: "/bʁymø/",
    partOfSpeech: "adjective",
    gender: null,
    emoji: "🌫️",
    exampleFr: "Le matin est brumeux près de la côte.",
    exampleEn: "The morning is misty near the coast.",
  },
  {
    id: "nor-ferme",
    regionId: "normandie",
    french: "une ferme",
    search: "ferme",
    english: "a farm",
    ipa: "/yn fɛʁm/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🐄",
    exampleFr: "Nous visitons une ferme qui fabrique du fromage.",
    exampleEn: "We are visiting a farm that makes cheese.",
  },

  // Bretagne
  {
    id: "bre-phare",
    regionId: "bretagne",
    french: "un phare",
    search: "phare",
    english: "a lighthouse",
    ipa: "/œ̃ faʁ/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🚨",
    exampleFr: "Le phare guide les bateaux pendant la nuit.",
    exampleEn: "The lighthouse guides boats during the night.",
  },
  {
    id: "bre-crepe",
    regionId: "bretagne",
    french: "une crêpe",
    search: "crepe",
    english: "a crêpe",
    ipa: "/yn kʁɛp/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🥞",
    exampleFr: "Je commande une crêpe au caramel au beurre salé.",
    exampleEn: "I am ordering a crêpe with salted-butter caramel.",
  },
  {
    id: "bre-sentier-cotier",
    regionId: "bretagne",
    french: "le sentier côtier",
    search: "sentier cotier",
    english: "the coastal path",
    ipa: "/lə sɑ̃tje kotje/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🥾",
    exampleFr: "Le sentier côtier longe une mer turquoise.",
    exampleEn: "The coastal path follows a turquoise sea.",
  },
  {
    id: "bre-naviguer",
    regionId: "bretagne",
    french: "naviguer",
    search: "naviguer",
    english: "to sail / navigate",
    ipa: "/naviɡe/",
    partOfSpeech: "verb",
    gender: null,
    emoji: "⛵",
    exampleFr: "Nous apprenons à naviguer dans la baie.",
    exampleEn: "We are learning to sail in the bay.",
  },
  {
    id: "bre-sale",
    regionId: "bretagne",
    french: "salé",
    search: "sale",
    english: "salty / salted",
    ipa: "/sale/",
    partOfSpeech: "adjective",
    gender: null,
    emoji: "🧂",
    exampleFr: "L'air est frais et salé au bord de l'océan.",
    exampleEn: "The air is fresh and salty by the ocean.",
  },

  // Pays de la Loire
  {
    id: "pdl-estuaire",
    regionId: "pays-de-la-loire",
    french: "l'estuaire",
    search: "estuaire",
    english: "the estuary",
    ipa: "/lɛstɥɛʁ/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🌅",
    exampleFr: "L'estuaire de la Loire s'ouvre sur l'Atlantique.",
    exampleEn: "The Loire estuary opens onto the Atlantic.",
  },
  {
    id: "pdl-marais",
    regionId: "pays-de-la-loire",
    french: "un marais",
    search: "marais",
    english: "a marsh",
    ipa: "/œ̃ maʁɛ/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🪷",
    exampleFr: "Le marais abrite de nombreux oiseaux.",
    exampleEn: "The marsh is home to many birds.",
  },
  {
    id: "pdl-voile",
    regionId: "pays-de-la-loire",
    french: "la voile",
    search: "voile",
    english: "sailing / the sail",
    ipa: "/la vwal/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "⛵",
    exampleFr: "Nous faisons de la voile près de la côte.",
    exampleEn: "We go sailing near the coast.",
  },
  {
    id: "pdl-pecher",
    regionId: "pays-de-la-loire",
    french: "pêcher",
    search: "pecher",
    english: "to fish",
    ipa: "/peʃe/",
    partOfSpeech: "verb",
    gender: null,
    emoji: "🎣",
    exampleFr: "On peut pêcher depuis le petit port.",
    exampleEn: "You can fish from the small harbour.",
  },
  {
    id: "pdl-paisible",
    regionId: "pays-de-la-loire",
    french: "paisible",
    search: "paisible",
    english: "peaceful",
    ipa: "/pɛzibl/",
    partOfSpeech: "adjective",
    gender: null,
    emoji: "🕊️",
    exampleFr: "Ce village est paisible en automne.",
    exampleEn: "This village is peaceful in autumn.",
  },

  // Centre-Val de Loire
  {
    id: "cvl-chateau",
    regionId: "centre-val-de-loire",
    french: "un château",
    search: "chateau",
    english: "a castle",
    ipa: "/œ̃ ʃɑto/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🏰",
    exampleFr: "Le château se reflète dans la rivière.",
    exampleEn: "The castle is reflected in the river.",
  },
  {
    id: "cvl-jardin",
    regionId: "centre-val-de-loire",
    french: "un jardin",
    search: "jardin",
    english: "a garden",
    ipa: "/œ̃ ʒaʁdɛ̃/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🌳",
    exampleFr: "Le jardin est ouvert au public.",
    exampleEn: "The garden is open to the public.",
  },
  {
    id: "cvl-vallee",
    regionId: "centre-val-de-loire",
    french: "la vallée",
    search: "vallee",
    english: "the valley",
    ipa: "/la vale/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🏞️",
    exampleFr: "La vallée suit le cours de la Loire.",
    exampleEn: "The valley follows the course of the Loire.",
  },
  {
    id: "cvl-royal",
    regionId: "centre-val-de-loire",
    french: "royal",
    search: "royal",
    english: "royal",
    ipa: "/ʁwajal/",
    partOfSpeech: "adjective",
    gender: null,
    emoji: "👑",
    exampleFr: "Cette résidence royale date du seizième siècle.",
    exampleEn: "This royal residence dates from the sixteenth century.",
  },
  {
    id: "cvl-admirer",
    regionId: "centre-val-de-loire",
    french: "admirer",
    search: "admirer",
    english: "to admire",
    ipa: "/admiʁe/",
    partOfSpeech: "verb",
    gender: null,
    emoji: "👀",
    exampleFr: "Les visiteurs admirent les détails de la façade.",
    exampleEn: "The visitors admire the details of the façade.",
  },

  // Grand Est
  {
    id: "ges-marche-noel",
    regionId: "grand-est",
    french: "un marché de Noël",
    search: "marche de noel",
    english: "a Christmas market",
    ipa: "/œ̃ maʁʃe də nɔɛl/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🎄",
    exampleFr: "Le marché de Noël ouvre à la fin du mois.",
    exampleEn: "The Christmas market opens at the end of the month.",
  },
  {
    id: "ges-cathedrale",
    regionId: "grand-est",
    french: "une cathédrale",
    search: "cathedrale",
    english: "a cathedral",
    ipa: "/yn katedʁal/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "⛪",
    exampleFr: "La cathédrale possède de magnifiques vitraux.",
    exampleEn: "The cathedral has magnificent stained-glass windows.",
  },
  {
    id: "ges-cigogne",
    regionId: "grand-est",
    french: "une cigogne",
    search: "cigogne",
    english: "a stork",
    ipa: "/yn siɡɔɲ/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🪺",
    exampleFr: "Une cigogne construit son nid sur le toit.",
    exampleEn: "A stork is building its nest on the roof.",
  },
  {
    id: "ges-petillant",
    regionId: "grand-est",
    french: "pétillant",
    search: "petillant",
    english: "sparkling / fizzy",
    ipa: "/petijɑ̃/",
    partOfSpeech: "adjective",
    gender: null,
    emoji: "🫧",
    exampleFr: "Ce jus de pomme est légèrement pétillant.",
    exampleEn: "This apple juice is lightly sparkling.",
  },
  {
    id: "ges-celebrer",
    regionId: "grand-est",
    french: "célébrer",
    search: "celebrer",
    english: "to celebrate",
    ipa: "/selebʁe/",
    partOfSpeech: "verb",
    gender: null,
    emoji: "🎉",
    exampleFr: "Les habitants célèbrent le retour du printemps.",
    exampleEn: "The residents celebrate the return of spring.",
  },

  // Bourgogne-Franche-Comté
  {
    id: "bfc-vignoble",
    regionId: "bourgogne-franche-comte",
    french: "un vignoble",
    search: "vignoble",
    english: "a vineyard",
    ipa: "/œ̃ viɲɔbl/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🍇",
    exampleFr: "Le vignoble couvre les collines voisines.",
    exampleEn: "The vineyard covers the nearby hills.",
  },
  {
    id: "bfc-fromage",
    regionId: "bourgogne-franche-comte",
    french: "le fromage",
    search: "fromage",
    english: "cheese",
    ipa: "/lə fʁɔmaʒ/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🧀",
    exampleFr: "Ce fromage a un goût délicat.",
    exampleEn: "This cheese has a delicate flavour.",
  },
  {
    id: "bfc-tonneau",
    regionId: "bourgogne-franche-comte",
    french: "un tonneau",
    search: "tonneau",
    english: "a barrel",
    ipa: "/œ̃ tono/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🛢️",
    exampleFr: "Le vin vieillit dans un tonneau en bois.",
    exampleEn: "The wine ages in a wooden barrel.",
  },
  {
    id: "bfc-deguster",
    regionId: "bourgogne-franche-comte",
    french: "déguster",
    search: "deguster",
    english: "to taste / savour",
    ipa: "/deɡyste/",
    partOfSpeech: "verb",
    gender: null,
    emoji: "🍽️",
    exampleFr: "Nous dégustons une spécialité locale.",
    exampleEn: "We are tasting a local speciality.",
  },
  {
    id: "bfc-boise",
    regionId: "bourgogne-franche-comte",
    french: "boisé",
    search: "boise",
    english: "wooded",
    ipa: "/bwaze/",
    partOfSpeech: "adjective",
    gender: null,
    emoji: "🌲",
    exampleFr: "Le sentier est boisé et ombragé.",
    exampleEn: "The path is wooded and shaded.",
  },

  // Nouvelle-Aquitaine
  {
    id: "naq-dune",
    regionId: "nouvelle-aquitaine",
    french: "une dune",
    search: "dune",
    english: "a dune",
    ipa: "/yn dyn/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🏖️",
    exampleFr: "Nous montons au sommet de la dune.",
    exampleEn: "We are climbing to the top of the dune.",
  },
  {
    id: "naq-surf",
    regionId: "nouvelle-aquitaine",
    french: "le surf",
    search: "surf",
    english: "surfing",
    ipa: "/lə sœʁf/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🏄",
    exampleFr: "Il pratique le surf chaque été.",
    exampleEn: "He goes surfing every summer.",
  },
  {
    id: "naq-huitre",
    regionId: "nouvelle-aquitaine",
    french: "une huître",
    search: "huitre",
    english: "an oyster",
    ipa: "/yn ɥitʁ/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🦪",
    exampleFr: "Elle goûte une huître fraîche du bassin.",
    exampleEn: "She tastes a fresh oyster from the bay.",
  },
  {
    id: "naq-vaste",
    regionId: "nouvelle-aquitaine",
    french: "vaste",
    search: "vaste",
    english: "vast / spacious",
    ipa: "/vast/",
    partOfSpeech: "adjective",
    gender: null,
    emoji: "↔️",
    exampleFr: "La plage est vaste et presque vide.",
    exampleEn: "The beach is vast and almost empty.",
  },
  {
    id: "naq-recolter",
    regionId: "nouvelle-aquitaine",
    french: "récolter",
    search: "recolter",
    english: "to harvest",
    ipa: "/ʁekɔlte/",
    partOfSpeech: "verb",
    gender: null,
    emoji: "🧺",
    exampleFr: "On récolte le raisin au début de l'automne.",
    exampleEn: "The grapes are harvested at the beginning of autumn.",
  },

  // Auvergne-Rhône-Alpes
  {
    id: "ara-volcan",
    regionId: "auvergne-rhone-alpes",
    french: "un volcan",
    search: "volcan",
    english: "a volcano",
    ipa: "/œ̃ vɔlkɑ̃/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🌋",
    exampleFr: "Ce volcan est endormi depuis des milliers d'années.",
    exampleEn: "This volcano has been dormant for thousands of years.",
  },
  {
    id: "ara-sommet",
    regionId: "auvergne-rhone-alpes",
    french: "un sommet",
    search: "sommet",
    english: "a summit / peak",
    ipa: "/œ̃ sɔmɛ/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "⛰️",
    exampleFr: "Le sommet reste couvert de neige.",
    exampleEn: "The summit remains covered with snow.",
  },
  {
    id: "ara-neige",
    regionId: "auvergne-rhone-alpes",
    french: "la neige",
    search: "neige",
    english: "snow",
    ipa: "/la nɛʒ/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "❄️",
    exampleFr: "Dans les Alpes, la neige tombe tôt.",
    exampleEn: "In the Alps, snow falls early.",
  },
  {
    id: "ara-randonner",
    regionId: "auvergne-rhone-alpes",
    french: "randonner",
    search: "randonner",
    english: "to hike",
    ipa: "/ʁɑ̃dɔne/",
    partOfSpeech: "verb",
    gender: null,
    emoji: "🥾",
    exampleFr: "Nous aimons randonner autour du lac.",
    exampleEn: "We like hiking around the lake.",
  },
  {
    id: "ara-escarpe",
    regionId: "auvergne-rhone-alpes",
    french: "escarpé",
    search: "escarpe",
    english: "steep",
    ipa: "/ɛskaʁpe/",
    partOfSpeech: "adjective",
    gender: null,
    emoji: "📈",
    exampleFr: "Le chemin est escarpé mais bien balisé.",
    exampleEn: "The path is steep but well marked.",
  },

  // Occitanie
  {
    id: "occ-place",
    regionId: "occitanie",
    french: "une place",
    search: "place",
    english: "a square",
    ipa: "/yn plas/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "⛲",
    exampleFr: "La place accueille un marché le samedi.",
    exampleEn: "The square hosts a market on Saturdays.",
  },
  {
    id: "occ-canal",
    regionId: "occitanie",
    french: "le canal",
    search: "canal",
    english: "the canal",
    ipa: "/lə kanal/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🚲",
    exampleFr: "Des platanes bordent le canal.",
    exampleEn: "Plane trees line the canal.",
  },
  {
    id: "occ-brique",
    regionId: "occitanie",
    french: "la brique",
    search: "brique",
    english: "brick",
    ipa: "/la bʁik/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🧱",
    exampleFr: "De nombreuses maisons sont construites en brique rose.",
    exampleEn: "Many houses are built from pink brick.",
  },
  {
    id: "occ-ensoleille",
    regionId: "occitanie",
    french: "ensoleillé",
    search: "ensoleille",
    english: "sunny",
    ipa: "/ɑ̃sɔleje/",
    partOfSpeech: "adjective",
    gender: null,
    emoji: "☀️",
    exampleFr: "Le ciel reste ensoleillé toute la journée.",
    exampleEn: "The sky stays sunny all day.",
  },
  {
    id: "occ-flaner",
    regionId: "occitanie",
    french: "flâner",
    search: "flaner",
    english: "to stroll / wander",
    ipa: "/flɑne/",
    partOfSpeech: "verb",
    gender: null,
    emoji: "🚶",
    exampleFr: "Nous aimons flâner dans les petites rues.",
    exampleEn: "We like strolling through the small streets.",
  },

  // Provence-Alpes-Côte d'Azur
  {
    id: "paca-calanque",
    regionId: "provence-alpes-cote-d-azur",
    french: "une calanque",
    search: "calanque",
    english: "a rocky Mediterranean inlet",
    ipa: "/yn kalɑ̃k/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🏞️",
    exampleFr: "Un sentier descend vers une calanque tranquille.",
    exampleEn: "A path descends towards a quiet rocky inlet.",
  },
  {
    id: "paca-lavande",
    regionId: "provence-alpes-cote-d-azur",
    french: "la lavande",
    search: "lavande",
    english: "lavender",
    ipa: "/la lavɑ̃d/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🪻",
    exampleFr: "La lavande fleurit au début de l'été.",
    exampleEn: "Lavender blooms at the beginning of summer.",
  },
  {
    id: "paca-petanque",
    regionId: "provence-alpes-cote-d-azur",
    french: "la pétanque",
    search: "petanque",
    english: "pétanque",
    ipa: "/la petɑ̃k/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🔵",
    exampleFr: "Ils jouent à la pétanque sous les platanes.",
    exampleEn: "They play pétanque under the plane trees.",
  },
  {
    id: "paca-provencal",
    regionId: "provence-alpes-cote-d-azur",
    french: "provençal",
    search: "provencal",
    english: "Provençal",
    ipa: "/pʁɔvɑ̃sal/",
    partOfSpeech: "adjective",
    gender: null,
    emoji: "🧺",
    exampleFr: "Ce marché provençal vend des herbes parfumées.",
    exampleEn: "This Provençal market sells fragrant herbs.",
  },
  {
    id: "paca-se-baigner",
    regionId: "provence-alpes-cote-d-azur",
    french: "se baigner",
    search: "se baigner",
    english: "to swim / bathe",
    ipa: "/sə bɛɲe/",
    partOfSpeech: "pronominal verb",
    gender: null,
    emoji: "🏊",
    exampleFr: "On peut se baigner ici dès le mois de juin.",
    exampleEn: "You can swim here from June onwards.",
  },

  // Corse
  {
    id: "cor-ile",
    regionId: "corse",
    french: "une île",
    search: "ile",
    english: "an island",
    ipa: "/yn il/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🏝️",
    exampleFr: "La Corse est une île montagneuse de la Méditerranée.",
    exampleEn: "Corsica is a mountainous island in the Mediterranean.",
  },
  {
    id: "cor-maquis",
    regionId: "corse",
    french: "le maquis",
    search: "maquis",
    english: "Mediterranean scrubland",
    ipa: "/lə maki/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🌿",
    exampleFr: "Le maquis couvre une grande partie de la colline.",
    exampleEn: "The scrubland covers a large part of the hill.",
  },
  {
    id: "cor-village-perche",
    regionId: "corse",
    french: "un village perché",
    search: "village perche",
    english: "a hilltop village",
    ipa: "/œ̃ vilaʒ pɛʁʃe/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🏘️",
    exampleFr: "Un village perché domine la vallée.",
    exampleEn: "A hilltop village overlooks the valley.",
  },
  {
    id: "cor-sauvage",
    regionId: "corse",
    french: "sauvage",
    search: "sauvage",
    english: "wild / unspoilt",
    ipa: "/sovaʒ/",
    partOfSpeech: "adjective",
    gender: null,
    emoji: "🦅",
    exampleFr: "Cette plage reste sauvage et silencieuse.",
    exampleEn: "This beach remains unspoilt and quiet.",
  },
  {
    id: "cor-traverser",
    regionId: "corse",
    french: "traverser",
    search: "traverser",
    english: "to cross",
    ipa: "/tʁavɛʁse/",
    partOfSpeech: "verb",
    gender: null,
    emoji: "🥾",
    exampleFr: "Nous traversons la montagne par un ancien sentier.",
    exampleEn: "We cross the mountain on an old path.",
  },

  // Guadeloupe
  {
    id: "gua-archipel",
    regionId: "guadeloupe",
    french: "un archipel",
    search: "archipel",
    english: "an archipelago",
    ipa: "/œ̃n aʁʃipɛl/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🗺️",
    exampleFr: "La Guadeloupe est un archipel des Caraïbes.",
    exampleEn: "Guadeloupe is an archipelago in the Caribbean.",
  },
  {
    id: "gua-mangrove",
    regionId: "guadeloupe",
    french: "la mangrove",
    search: "mangrove",
    english: "the mangrove forest",
    ipa: "/la mɑ̃ɡʁɔv/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🌿",
    exampleFr: "La mangrove protège la côte et abrite des oiseaux.",
    exampleEn: "The mangrove protects the coast and shelters birds.",
  },
  {
    id: "gua-colibri",
    regionId: "guadeloupe",
    french: "un colibri",
    search: "colibri",
    english: "a hummingbird",
    ipa: "/œ̃ kɔlibʁi/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🐦",
    exampleFr: "Un colibri se pose près d'une fleur rouge.",
    exampleEn: "A hummingbird lands near a red flower.",
  },
  {
    id: "gua-creole",
    regionId: "guadeloupe",
    french: "le créole",
    search: "creole",
    english: "Creole language",
    ipa: "/lə kʁeɔl/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "💬",
    exampleFr: "Le créole guadeloupéen est parlé aux côtés du français.",
    exampleEn: "Guadeloupean Creole is spoken alongside French.",
  },
  {
    id: "gua-epice",
    regionId: "guadeloupe",
    french: "épicé",
    search: "epice",
    english: "spicy / seasoned",
    ipa: "/epise/",
    partOfSpeech: "adjective",
    gender: null,
    emoji: "🌶️",
    exampleFr: "Cette sauce est douce et légèrement épicée.",
    exampleEn: "This sauce is mild and lightly spiced.",
  },

  // Martinique
  {
    id: "mar-yole",
    regionId: "martinique",
    french: "une yole",
    search: "yole",
    english: "a traditional sailing boat",
    ipa: "/yn jɔl/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "⛵",
    exampleFr: "La yole avance rapidement grâce au vent.",
    exampleEn: "The yole moves quickly thanks to the wind.",
  },
  {
    id: "mar-canne-sucre",
    regionId: "martinique",
    french: "la canne à sucre",
    search: "canne a sucre",
    english: "sugar cane",
    ipa: "/la kan a sykʁ/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🌾",
    exampleFr: "La canne à sucre pousse sous le soleil tropical.",
    exampleEn: "Sugar cane grows under the tropical sun.",
  },
  {
    id: "mar-jardin-tropical",
    regionId: "martinique",
    french: "un jardin tropical",
    search: "jardin tropical",
    english: "a tropical garden",
    ipa: "/œ̃ ʒaʁdɛ̃ tʁɔpikal/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🌺",
    exampleFr: "Le jardin tropical rassemble des plantes colorées.",
    exampleEn: "The tropical garden brings together colourful plants.",
  },
  {
    id: "mar-ramer",
    regionId: "martinique",
    french: "ramer",
    search: "ramer",
    english: "to row",
    ipa: "/ʁame/",
    partOfSpeech: "verb",
    gender: null,
    emoji: "🚣",
    exampleFr: "L'équipe doit ramer au même rythme.",
    exampleEn: "The team must row at the same pace.",
  },
  {
    id: "mar-fleuri",
    regionId: "martinique",
    french: "fleuri",
    search: "fleuri",
    english: "flower-filled / in bloom",
    ipa: "/flœʁi/",
    partOfSpeech: "adjective",
    gender: null,
    emoji: "🌸",
    exampleFr: "Le chemin fleuri traverse le village.",
    exampleEn: "The flower-lined path crosses the village.",
  },

  // Guyane
  {
    id: "guy-foret-tropicale",
    regionId: "guyane",
    french: "la forêt tropicale",
    search: "foret tropicale",
    english: "the tropical rainforest",
    ipa: "/la fɔʁɛ tʁɔpikal/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🌳",
    exampleFr: "La forêt tropicale couvre une grande partie de la Guyane.",
    exampleEn: "The tropical rainforest covers a large part of French Guiana.",
  },
  {
    id: "guy-fleuve",
    regionId: "guyane",
    french: "un fleuve",
    search: "fleuve",
    english: "a river that flows to the sea",
    ipa: "/œ̃ flœv/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🛶",
    exampleFr: "Le fleuve sert de voie de transport entre les villages.",
    exampleEn: "The river serves as a transport route between villages.",
  },
  {
    id: "guy-centre-spatial",
    regionId: "guyane",
    french: "le centre spatial",
    search: "centre spatial",
    english: "the space centre",
    ipa: "/lə sɑ̃tʁ spasjal/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🛰️",
    exampleFr: "Le centre spatial se trouve près de Kourou.",
    exampleEn: "The space centre is located near Kourou.",
  },
  {
    id: "guy-decoller",
    regionId: "guyane",
    french: "décoller",
    search: "decoller",
    english: "to take off",
    ipa: "/dekɔle/",
    partOfSpeech: "verb",
    gender: null,
    emoji: "🚀",
    exampleFr: "La fusée va décoller dans quelques minutes.",
    exampleEn: "The rocket is going to take off in a few minutes.",
  },
  {
    id: "guy-immense",
    regionId: "guyane",
    french: "immense",
    search: "immense",
    english: "immense / vast",
    ipa: "/imɑ̃s/",
    partOfSpeech: "adjective",
    gender: null,
    emoji: "🌎",
    exampleFr: "Depuis le bateau, la forêt semble immense.",
    exampleEn: "From the boat, the forest seems immense.",
  },

  // La Réunion
  {
    id: "reu-cirque",
    regionId: "la-reunion",
    french: "un cirque",
    search: "cirque",
    english: "a natural mountain amphitheatre",
    ipa: "/œ̃ siʁk/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🏞️",
    exampleFr: "Le cirque de Mafate est entouré de hautes montagnes.",
    exampleEn: "The Cirque de Mafate is surrounded by high mountains.",
  },
  {
    id: "reu-piton",
    regionId: "la-reunion",
    french: "un piton",
    search: "piton",
    english: "a sharp peak",
    ipa: "/œ̃ pitɔ̃/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🌋",
    exampleFr: "Un nuage cache le sommet du piton.",
    exampleEn: "A cloud hides the summit of the peak.",
  },
  {
    id: "reu-cascade",
    regionId: "la-reunion",
    french: "une cascade",
    search: "cascade",
    english: "a waterfall",
    ipa: "/yn kaskad/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "💧",
    exampleFr: "La cascade tombe dans un bassin naturel.",
    exampleEn: "The waterfall drops into a natural pool.",
  },
  {
    id: "reu-gravir",
    regionId: "la-reunion",
    french: "gravir",
    search: "gravir",
    english: "to climb",
    ipa: "/ɡʁaviʁ/",
    partOfSpeech: "verb",
    gender: null,
    emoji: "🧗",
    exampleFr: "Nous partons tôt pour gravir le volcan.",
    exampleEn: "We leave early to climb the volcano.",
  },
  {
    id: "reu-volcanique",
    regionId: "la-reunion",
    french: "volcanique",
    search: "volcanique",
    english: "volcanic",
    ipa: "/vɔlkanik/",
    partOfSpeech: "adjective",
    gender: null,
    emoji: "🪨",
    exampleFr: "Le paysage volcanique change après chaque éruption.",
    exampleEn: "The volcanic landscape changes after each eruption.",
  },

  // Mayotte
  {
    id: "may-lagon",
    regionId: "mayotte",
    french: "un lagon",
    search: "lagon",
    english: "a lagoon",
    ipa: "/œ̃ laɡɔ̃/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🌊",
    exampleFr: "Le lagon abrite une grande diversité de poissons.",
    exampleEn: "The lagoon is home to a wide variety of fish.",
  },
  {
    id: "may-tortue-marine",
    regionId: "mayotte",
    french: "une tortue marine",
    search: "tortue marine",
    english: "a sea turtle",
    ipa: "/yn tɔʁty maʁin/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🐢",
    exampleFr: "Une tortue marine nage près de la plage.",
    exampleEn: "A sea turtle swims near the beach.",
  },
  {
    id: "may-barriere-corail",
    regionId: "mayotte",
    french: "une barrière de corail",
    search: "barriere de corail",
    english: "a coral reef barrier",
    ipa: "/yn baʁjɛʁ də kɔʁaj/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🪸",
    exampleFr: "Une barrière de corail entoure une grande partie du lagon.",
    exampleEn: "A coral reef barrier surrounds much of the lagoon.",
  },
  {
    id: "may-pagayer",
    regionId: "mayotte",
    french: "pagayer",
    search: "pagayer",
    english: "to paddle",
    ipa: "/paɡeje/",
    partOfSpeech: "verb",
    gender: null,
    emoji: "🛶",
    exampleFr: "Nous allons pagayer calmement dans le lagon.",
    exampleEn: "We are going to paddle calmly in the lagoon.",
  },
  {
    id: "may-preserve",
    regionId: "mayotte",
    french: "préservé",
    search: "preserve",
    english: "protected / unspoilt",
    ipa: "/pʁezeʁve/",
    partOfSpeech: "adjective",
    gender: null,
    emoji: "🛡️",
    exampleFr: "Cet espace naturel est fragile et préservé.",
    exampleEn: "This natural area is fragile and protected.",
  },
] as const satisfies readonly Word[];

export const MASTERY_STAGE_LABELS = [
  "Nouveau",
  "Découverte",
  "En pratique",
  "Familier",
  "Solide",
  "Maîtrisé",
  "Acquis",
] as const;

export type LeaderboardEntry = {
  rank: number;
  name: string;
  xp: number;
  streak: number;
  avatar: string;
};

export const SEED_LEADERBOARD = [
  { rank: 1, name: "Maya", xp: 2840, streak: 18, avatar: "🦊" },
  { rank: 2, name: "Théo", xp: 2510, streak: 12, avatar: "🐻" },
  { rank: 3, name: "Amira", xp: 2290, streak: 21, avatar: "🐦" },
  { rank: 4, name: "Louis", xp: 1980, streak: 9, avatar: "🐢" },
  { rank: 5, name: "You", xp: 1640, streak: 7, avatar: "🌟" },
] as const satisfies readonly LeaderboardEntry[];

export type CollectibleRarity =
  | "common"
  | "uncommon"
  | "rare"
  | "epic"
  | "legendary";

export type Collectible = {
  id: string;
  name: string;
  emoji: string;
  rarity: CollectibleRarity;
  description: string;
  unlockAtXp: number;
};

export const SEED_COLLECTIBLES = [
  {
    id: "metro-ticket",
    name: "Metro Ticket",
    emoji: "🎟️",
    rarity: "common",
    description: "Your first souvenir from the capital.",
    unlockAtXp: 100,
  },
  {
    id: "lighthouse-pin",
    name: "Lighthouse Pin",
    emoji: "🗼",
    rarity: "uncommon",
    description: "A bright marker from the Atlantic coast.",
    unlockAtXp: 400,
  },
  {
    id: "castle-key",
    name: "Castle Key",
    emoji: "🗝️",
    rarity: "rare",
    description: "A key said to open a Loire Valley gate.",
    unlockAtXp: 900,
  },
  {
    id: "alpine-badge",
    name: "Alpine Badge",
    emoji: "🏔️",
    rarity: "epic",
    description: "Earned after climbing through a difficult review set.",
    unlockAtXp: 1600,
  },
  {
    id: "golden-compass",
    name: "Golden Compass",
    emoji: "🧭",
    rarity: "legendary",
    description: "For travellers who keep finding their way back to French.",
    unlockAtXp: 3000,
  },
] as const satisfies readonly Collectible[];

export const regions = REGIONS;
export const words = WORDS;
