import {
  CEFR_LEVELS,
  type CefrLevel,
} from "./curriculum-metadata";

export { CEFR_LEVELS };
export type { CefrLevel };

export type Region = {
  id: string;
  name: string;
  shortLabel: string;
  number: number;
  emoji: string;
  theme: string;
  cultureNote: string;
  accentColor: string;
};

export type GrammaticalGender = "masculine" | "feminine";

export type PartOfSpeech =
  | "noun"
  | "verb"
  | "pronominal verb"
  | "adjective"
  | "adverb"
  | "phrase";

/**
 * Lesson numbering is intentionally open-ended. The checked-in French
 * foundation currently has three lessons per region, while CMS-authored
 * courses may add later CEFR stages without a schema or type migration.
 */
export type CurriculumLessonNumber = number;

export type Word = {
  id: string;
  regionId: Region["id"];
  french: string;
  search: string;
  english: string;
  ipa: string;
  partOfSpeech: PartOfSpeech;
  gender: GrammaticalGender | null;
  emoji: string;
  exampleFr: string;
  exampleEn: string;
  cefr: CefrLevel;
  topic: string;
  lesson: CurriculumLessonNumber;
};

type FoundationWord = Omit<Word, "cefr" | "topic" | "lesson">;

export const REGIONS = [
  {
    id: "ile-de-france",
    name: "Île-de-France",
    shortLabel: "Paris",
    number: 1,
    emoji: "🏙️",
    theme: "City rhythm and culture",
    cultureNote:
      "Museums, neighbourhood cafés and a vast rail network make the capital region ideal for practical city French.",
    accentColor: "#315C8C",
  },
  {
    id: "hauts-de-france",
    name: "Hauts-de-France",
    shortLabel: "The North",
    number: 2,
    emoji: "🔔",
    theme: "Markets and warm welcomes",
    cultureNote:
      "The region is known for its belfries, festive street markets and a strong tradition of hospitality.",
    accentColor: "#2E7180",
  },
  {
    id: "normandie",
    name: "Normandie",
    shortLabel: "Normandy",
    number: 3,
    emoji: "🌊",
    theme: "Cliffs, tides and orchards",
    cultureNote:
      "Dramatic coastal scenery, dairy farms and apple orchards shape Normandy's everyday vocabulary.",
    accentColor: "#56658F",
  },
  {
    id: "bretagne",
    name: "Bretagne",
    shortLabel: "Brittany",
    number: 4,
    emoji: "⚓",
    theme: "Sea roads and crêpes",
    cultureNote:
      "Brittany's lighthouses, coastal paths and maritime traditions invite learners to speak about the sea.",
    accentColor: "#2E4C5C",
  },
  {
    id: "pays-de-la-loire",
    name: "Pays de la Loire",
    shortLabel: "Atlantic Loire",
    number: 5,
    emoji: "⛵",
    theme: "Estuary and wetlands",
    cultureNote:
      "Where the Loire reaches the Atlantic, estuary towns, marshes and sailing shape life near the water.",
    accentColor: "#2D7A6E",
  },
  {
    id: "centre-val-de-loire",
    name: "Centre-Val de Loire",
    shortLabel: "Loire Valley",
    number: 6,
    emoji: "🏰",
    theme: "Castles and gardens",
    cultureNote:
      "Renaissance châteaux and carefully designed gardens tell the story of France's royal valley.",
    accentColor: "#557A3A",
  },
  {
    id: "grand-est",
    name: "Grand Est",
    shortLabel: "Grand Est",
    number: 7,
    emoji: "🎄",
    theme: "Festivals and borderlands",
    cultureNote:
      "Cathedral cities, Christmas markets and cross-border traditions give the region a distinctive character.",
    accentColor: "#7B4B73",
  },
  {
    id: "bourgogne-franche-comte",
    name: "Bourgogne-Franche-Comté",
    shortLabel: "Burgundy",
    number: 8,
    emoji: "🍇",
    theme: "Vineyards and craft",
    cultureNote:
      "Vineyards, cellars, cheeses and wooded hills make this a rich region for food and landscape vocabulary.",
    accentColor: "#7A5236",
  },
  {
    id: "nouvelle-aquitaine",
    name: "Nouvelle-Aquitaine",
    shortLabel: "Aquitaine",
    number: 9,
    emoji: "🏄",
    theme: "Ocean and wide horizons",
    cultureNote:
      "Atlantic beaches, oyster beds, dunes and vineyards stretch across France's largest metropolitan region.",
    accentColor: "#2D718C",
  },
  {
    id: "auvergne-rhone-alpes",
    name: "Auvergne-Rhône-Alpes",
    shortLabel: "Alps and Auvergne",
    number: 10,
    emoji: "🏔️",
    theme: "Volcanoes and high trails",
    cultureNote:
      "Ancient volcanoes meet Alpine summits in a region made for mountain, weather and hiking vocabulary.",
    accentColor: "#5F5B8C",
  },
  {
    id: "occitanie",
    name: "Occitanie",
    shortLabel: "Occitanie",
    number: 11,
    emoji: "🧱",
    theme: "Canals and sunlit squares",
    cultureNote:
      "Pink-brick cities, the Canal du Midi and lively public squares encourage a slower southern rhythm.",
    accentColor: "#B85C46",
  },
  {
    id: "provence-alpes-cote-d-azur",
    name: "Provence-Alpes-Côte d'Azur",
    shortLabel: "Provence",
    number: 12,
    emoji: "🪻",
    theme: "Lavender and Mediterranean coves",
    cultureNote:
      "Provençal markets, limestone calanques and lavender fields bring scent, colour and outdoor life together.",
    accentColor: "#C77C2E",
  },
  {
    id: "corse",
    name: "Corse",
    shortLabel: "Corsica",
    number: 13,
    emoji: "🏝️",
    theme: "Island paths and wild coast",
    cultureNote:
      "Mountain villages, fragrant maquis and a rugged coastline give Corsica its strong island identity.",
    accentColor: "#8A4F4A",
  },
  {
    id: "guadeloupe",
    name: "Guadeloupe",
    shortLabel: "Guadeloupe",
    number: 14,
    emoji: "🦋",
    theme: "Archipelago and Creole culture",
    cultureNote:
      "This Caribbean archipelago brings together rainforest, mangroves, lively markets and a rich French and Creole culture.",
    accentColor: "#2F806F",
  },
  {
    id: "martinique",
    name: "Martinique",
    shortLabel: "Martinique",
    number: 15,
    emoji: "⛵",
    theme: "Volcanic shores and flower gardens",
    cultureNote:
      "Traditional yoles, tropical gardens and the slopes of Mount Pelée shape everyday life on this Caribbean island.",
    accentColor: "#A35C43",
  },
  {
    id: "guyane",
    name: "Guyane",
    shortLabel: "French Guiana",
    number: 16,
    emoji: "🚀",
    theme: "Rainforest, rivers and space",
    cultureNote:
      "Amazonian forest and great rivers surround diverse towns, while rockets launch from the Guiana Space Centre near Kourou.",
    accentColor: "#397449",
  },
  {
    id: "la-reunion",
    name: "La Réunion",
    shortLabel: "Réunion",
    number: 17,
    emoji: "🌋",
    theme: "Cirques, peaks and a living volcano",
    cultureNote:
      "Mountain cirques, waterfalls and Piton de la Fournaise meet a vibrant French and Réunion Creole culture in the Indian Ocean.",
    accentColor: "#92523B",
  },
  {
    id: "mayotte",
    name: "Mayotte",
    shortLabel: "Mayotte",
    number: 18,
    emoji: "🐢",
    theme: "Lagoon and island life",
    cultureNote:
      "A vast Indian Ocean lagoon, coral reefs and mangroves support sea turtles and a deeply multilingual island culture.",
    accentColor: "#267C8A",
  },
] as const satisfies readonly Region[];

export type RegionId = (typeof REGIONS)[number]["id"];

export type CurriculumLessonPlan = {
  lesson: CurriculumLessonNumber;
  title: string;
  topic: string;
  cefr: CefrLevel;
};

export type RegionCurriculumPlan = readonly CurriculumLessonPlan[];

export const CURRICULUM_PLAN = {
  "ile-de-france": [
    { lesson: 1, title: "Capital landmarks", topic: "city landmarks", cefr: "A1" },
    { lesson: 2, title: "Getting around", topic: "public transport", cefr: "A1" },
    { lesson: 3, title: "Everyday city life", topic: "neighbourhood life", cefr: "A2" },
  ],
  "hauts-de-france": [
    { lesson: 1, title: "A northern welcome", topic: "local welcome", cefr: "A1" },
    { lesson: 2, title: "At the market", topic: "market food", cefr: "A1" },
    { lesson: 3, title: "Town and weather", topic: "town weather", cefr: "A2" },
  ],
  normandie: [
    { lesson: 1, title: "Coast and countryside", topic: "coastal landscape", cefr: "A1" },
    { lesson: 2, title: "Orchard and dairy", topic: "farm food", cefr: "A1" },
    { lesson: 3, title: "A day by the sea", topic: "seaside weather", cefr: "A2" },
  ],
  bretagne: [
    { lesson: 1, title: "Life by the sea", topic: "maritime life", cefr: "A1" },
    { lesson: 2, title: "Around the harbour", topic: "harbour travel", cefr: "A1" },
    { lesson: 3, title: "The Breton table", topic: "regional food", cefr: "A2" },
  ],
  "pays-de-la-loire": [
    { lesson: 1, title: "Where river meets ocean", topic: "waterways", cefr: "A1" },
    { lesson: 2, title: "Coast and city", topic: "local transport", cefr: "A1" },
    { lesson: 3, title: "A local outing", topic: "outdoor leisure", cefr: "A2" },
  ],
  "centre-val-de-loire": [
    { lesson: 1, title: "Royal valley", topic: "heritage", cefr: "A1" },
    { lesson: 2, title: "Visiting a château", topic: "visitor essentials", cefr: "A1" },
    { lesson: 3, title: "Along the Loire", topic: "river countryside", cefr: "A2" },
  ],
  "grand-est": [
    { lesson: 1, title: "Winter traditions", topic: "seasonal traditions", cefr: "A1" },
    { lesson: 2, title: "Across the city", topic: "border city travel", cefr: "A1" },
    { lesson: 3, title: "Food and craft", topic: "regional craft", cefr: "A2" },
  ],
  "bourgogne-franche-comte": [
    { lesson: 1, title: "Vineyard country", topic: "vineyard landscape", cefr: "A1" },
    { lesson: 2, title: "At the table", topic: "food and drink", cefr: "A1" },
    { lesson: 3, title: "Rural heritage", topic: "village craft", cefr: "A2" },
  ],
  "nouvelle-aquitaine": [
    { lesson: 1, title: "Ocean horizons", topic: "Atlantic coast", cefr: "A1" },
    { lesson: 2, title: "Market and vineyard", topic: "market produce", cefr: "A1" },
    { lesson: 3, title: "Exploring the southwest", topic: "cycling and nature", cefr: "A2" },
  ],
  "auvergne-rhone-alpes": [
    { lesson: 1, title: "Mountain landscapes", topic: "mountain nature", cefr: "A1" },
    { lesson: 2, title: "Cold-weather kit", topic: "winter clothing", cefr: "A1" },
    { lesson: 3, title: "High-altitude outings", topic: "mountain activities", cefr: "A2" },
  ],
  occitanie: [
    { lesson: 1, title: "Southern city life", topic: "city squares", cefr: "A1" },
    { lesson: 2, title: "Along the canal", topic: "canal travel", cefr: "A1" },
    { lesson: 3, title: "Market and countryside", topic: "southern produce", cefr: "A2" },
  ],
  "provence-alpes-cote-d-azur": [
    { lesson: 1, title: "Mediterranean landscapes", topic: "Mediterranean nature", cefr: "A1" },
    { lesson: 2, title: "Scents of the market", topic: "market flavours", cefr: "A1" },
    { lesson: 3, title: "A summer on the coast", topic: "coastal leisure", cefr: "A2" },
  ],
  corse: [
    { lesson: 1, title: "Island landscape", topic: "island nature", cefr: "A1" },
    { lesson: 2, title: "Village and food", topic: "village food", cefr: "A1" },
    { lesson: 3, title: "On the trail", topic: "island hiking", cefr: "A2" },
  ],
  guadeloupe: [
    { lesson: 1, title: "The butterfly islands", topic: "island ecology", cefr: "A1" },
    { lesson: 2, title: "Market and beach", topic: "tropical food", cefr: "A1" },
    { lesson: 3, title: "Tropical weather", topic: "rainforest weather", cefr: "A2" },
  ],
  martinique: [
    { lesson: 1, title: "Island traditions", topic: "island traditions", cefr: "A1" },
    { lesson: 2, title: "Garden and kitchen", topic: "tropical cooking", cefr: "A1" },
    { lesson: 3, title: "Coast and volcano", topic: "volcanic coast", cefr: "A2" },
  ],
  guyane: [
    { lesson: 1, title: "Forest and space", topic: "forest and space", cefr: "A1" },
    { lesson: 2, title: "River journey", topic: "river travel", cefr: "A1" },
    { lesson: 3, title: "Wildlife and climate", topic: "rainforest wildlife", cefr: "A2" },
  ],
  "la-reunion": [
    { lesson: 1, title: "Volcanic island", topic: "volcanic landscape", cefr: "A1" },
    { lesson: 2, title: "Trail and viewpoint", topic: "mountain trails", cefr: "A1" },
    { lesson: 3, title: "Creole table and trade winds", topic: "island food and weather", cefr: "A2" },
  ],
  mayotte: [
    { lesson: 1, title: "Life in the lagoon", topic: "lagoon ecology", cefr: "A1" },
    { lesson: 2, title: "Island community", topic: "community life", cefr: "A1" },
    { lesson: 3, title: "Protecting the coast", topic: "coastal conservation", cefr: "A2" },
  ],
} as const satisfies Record<RegionId, RegionCurriculumPlan>;

const FOUNDATION_WORDS = [
  // Île-de-France
  {
    id: "idf-metro",
    regionId: "ile-de-france",
    french: "le métro",
    search: "metro",
    english: "the metro / subway",
    ipa: "/lə metʁo/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🚇",
    exampleFr: "Le métro passe toutes les trois minutes.",
    exampleEn: "The metro comes every three minutes.",
  },
  {
    id: "idf-musee",
    regionId: "ile-de-france",
    french: "un musée",
    search: "musee",
    english: "a museum",
    ipa: "/œ̃ myze/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🖼️",
    exampleFr: "Nous visitons un musée après le déjeuner.",
    exampleEn: "We are visiting a museum after lunch.",
  },
  {
    id: "idf-banlieue",
    regionId: "ile-de-france",
    french: "la banlieue",
    search: "banlieue",
    english: "the suburbs",
    ipa: "/la bɑ̃ljø/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🏘️",
    exampleFr: "Elle habite en banlieue et travaille à Paris.",
    exampleEn: "She lives in the suburbs and works in Paris.",
  },
  {
    id: "idf-se-depecher",
    regionId: "ile-de-france",
    french: "se dépêcher",
    search: "se depecher",
    english: "to hurry",
    ipa: "/sə depeʃe/",
    partOfSpeech: "pronominal verb",
    gender: null,
    emoji: "⏱️",
    exampleFr: "Il faut se dépêcher pour ne pas rater le train.",
    exampleEn: "We have to hurry so we do not miss the train.",
  },
  {
    id: "idf-anime",
    regionId: "ile-de-france",
    french: "animé",
    search: "anime",
    english: "lively / bustling",
    ipa: "/anime/",
    partOfSpeech: "adjective",
    gender: null,
    emoji: "✨",
    exampleFr: "Le quartier est animé le vendredi soir.",
    exampleEn: "The neighbourhood is lively on Friday evening.",
  },

  // Hauts-de-France
  {
    id: "hdf-braderie",
    regionId: "hauts-de-france",
    french: "la braderie",
    search: "braderie",
    english: "the street market / clearance sale",
    ipa: "/la bʁadʁi/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🛍️",
    exampleFr: "La braderie remplit les rues de stands colorés.",
    exampleEn: "The street market fills the streets with colourful stalls.",
  },
  {
    id: "hdf-beffroi",
    regionId: "hauts-de-france",
    french: "un beffroi",
    search: "beffroi",
    english: "a belfry",
    ipa: "/œ̃ befʁwa/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🔔",
    exampleFr: "Le beffroi domine la place centrale.",
    exampleEn: "The belfry overlooks the central square.",
  },
  {
    id: "hdf-gaufre",
    regionId: "hauts-de-france",
    french: "une gaufre",
    search: "gaufre",
    english: "a waffle",
    ipa: "/yn ɡofʁ/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🧇",
    exampleFr: "La gaufre est encore chaude.",
    exampleEn: "The waffle is still warm.",
  },
  {
    id: "hdf-chaleureux",
    regionId: "hauts-de-france",
    french: "chaleureux",
    search: "chaleureux",
    english: "warm / welcoming",
    ipa: "/ʃaløʁø/",
    partOfSpeech: "adjective",
    gender: null,
    emoji: "🤗",
    exampleFr: "Les habitants nous réservent un accueil chaleureux.",
    exampleEn: "The residents give us a warm welcome.",
  },
  {
    id: "hdf-accueillir",
    regionId: "hauts-de-france",
    french: "accueillir",
    search: "accueillir",
    english: "to welcome",
    ipa: "/akœjiʁ/",
    partOfSpeech: "verb",
    gender: null,
    emoji: "👋",
    exampleFr: "Le serveur nous accueille avec le sourire.",
    exampleEn: "The waiter welcomes us with a smile.",
  },

  // Normandie
  {
    id: "nor-falaise",
    regionId: "normandie",
    french: "une falaise",
    search: "falaise",
    english: "a cliff",
    ipa: "/yn falɛz/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🪨",
    exampleFr: "La falaise domine la mer.",
    exampleEn: "The cliff overlooks the sea.",
  },
  {
    id: "nor-cidre",
    regionId: "normandie",
    french: "le cidre",
    search: "cidre",
    english: "cider",
    ipa: "/lə sidʁ/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🍎",
    exampleFr: "Le cidre normand accompagne le repas.",
    exampleEn: "Norman cider accompanies the meal.",
  },
  {
    id: "nor-maree",
    regionId: "normandie",
    french: "la marée",
    search: "maree",
    english: "the tide",
    ipa: "/la maʁe/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🌊",
    exampleFr: "La marée monte rapidement ce soir.",
    exampleEn: "The tide is rising quickly this evening.",
  },
  {
    id: "nor-brumeux",
    regionId: "normandie",
    french: "brumeux",
    search: "brumeux",
    english: "misty / foggy",
    ipa: "/bʁymø/",
    partOfSpeech: "adjective",
    gender: null,
    emoji: "🌫️",
    exampleFr: "Le matin est brumeux près de la côte.",
    exampleEn: "The morning is misty near the coast.",
  },
  {
    id: "nor-ferme",
    regionId: "normandie",
    french: "une ferme",
    search: "ferme",
    english: "a farm",
    ipa: "/yn fɛʁm/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🐄",
    exampleFr: "Nous visitons une ferme qui fabrique du fromage.",
    exampleEn: "We are visiting a farm that makes cheese.",
  },

  // Bretagne
  {
    id: "bre-phare",
    regionId: "bretagne",
    french: "un phare",
    search: "phare",
    english: "a lighthouse",
    ipa: "/œ̃ faʁ/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🚨",
    exampleFr: "Le phare guide les bateaux pendant la nuit.",
    exampleEn: "The lighthouse guides boats during the night.",
  },
  {
    id: "bre-crepe",
    regionId: "bretagne",
    french: "une crêpe",
    search: "crepe",
    english: "a crêpe",
    ipa: "/yn kʁɛp/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🥞",
    exampleFr: "Je commande une crêpe au caramel au beurre salé.",
    exampleEn: "I am ordering a crêpe with salted-butter caramel.",
  },
  {
    id: "bre-sentier-cotier",
    regionId: "bretagne",
    french: "le sentier côtier",
    search: "sentier cotier",
    english: "the coastal path",
    ipa: "/lə sɑ̃tje kotje/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🥾",
    exampleFr: "Le sentier côtier longe une mer turquoise.",
    exampleEn: "The coastal path follows a turquoise sea.",
  },
  {
    id: "bre-naviguer",
    regionId: "bretagne",
    french: "naviguer",
    search: "naviguer",
    english: "to sail / navigate",
    ipa: "/naviɡe/",
    partOfSpeech: "verb",
    gender: null,
    emoji: "⛵",
    exampleFr: "Nous apprenons à naviguer dans la baie.",
    exampleEn: "We are learning to sail in the bay.",
  },
  {
    id: "bre-sale",
    regionId: "bretagne",
    french: "salé",
    search: "sale",
    english: "salty / salted",
    ipa: "/sale/",
    partOfSpeech: "adjective",
    gender: null,
    emoji: "🧂",
    exampleFr: "L'air est frais et salé au bord de l'océan.",
    exampleEn: "The air is fresh and salty by the ocean.",
  },

  // Pays de la Loire
  {
    id: "pdl-estuaire",
    regionId: "pays-de-la-loire",
    french: "l'estuaire",
    search: "estuaire",
    english: "the estuary",
    ipa: "/lɛstɥɛʁ/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🌅",
    exampleFr: "L'estuaire de la Loire s'ouvre sur l'Atlantique.",
    exampleEn: "The Loire estuary opens onto the Atlantic.",
  },
  {
    id: "pdl-marais",
    regionId: "pays-de-la-loire",
    french: "un marais",
    search: "marais",
    english: "a marsh",
    ipa: "/œ̃ maʁɛ/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🪷",
    exampleFr: "Le marais abrite de nombreux oiseaux.",
    exampleEn: "The marsh is home to many birds.",
  },
  {
    id: "pdl-voile",
    regionId: "pays-de-la-loire",
    french: "la voile",
    search: "voile",
    english: "sailing / the sail",
    ipa: "/la vwal/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "⛵",
    exampleFr: "Nous faisons de la voile près de la côte.",
    exampleEn: "We go sailing near the coast.",
  },
  {
    id: "pdl-pecher",
    regionId: "pays-de-la-loire",
    french: "pêcher",
    search: "pecher",
    english: "to fish",
    ipa: "/peʃe/",
    partOfSpeech: "verb",
    gender: null,
    emoji: "🎣",
    exampleFr: "On peut pêcher depuis le petit port.",
    exampleEn: "You can fish from the small harbour.",
  },
  {
    id: "pdl-paisible",
    regionId: "pays-de-la-loire",
    french: "paisible",
    search: "paisible",
    english: "peaceful",
    ipa: "/pɛzibl/",
    partOfSpeech: "adjective",
    gender: null,
    emoji: "🕊️",
    exampleFr: "Ce village est paisible en automne.",
    exampleEn: "This village is peaceful in autumn.",
  },

  // Centre-Val de Loire
  {
    id: "cvl-chateau",
    regionId: "centre-val-de-loire",
    french: "un château",
    search: "chateau",
    english: "a castle",
    ipa: "/œ̃ ʃɑto/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🏰",
    exampleFr: "Le château se reflète dans la rivière.",
    exampleEn: "The castle is reflected in the river.",
  },
  {
    id: "cvl-jardin",
    regionId: "centre-val-de-loire",
    french: "un jardin",
    search: "jardin",
    english: "a garden",
    ipa: "/œ̃ ʒaʁdɛ̃/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🌳",
    exampleFr: "Le jardin est ouvert au public.",
    exampleEn: "The garden is open to the public.",
  },
  {
    id: "cvl-vallee",
    regionId: "centre-val-de-loire",
    french: "la vallée",
    search: "vallee",
    english: "the valley",
    ipa: "/la vale/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🏞️",
    exampleFr: "La vallée suit le cours de la Loire.",
    exampleEn: "The valley follows the course of the Loire.",
  },
  {
    id: "cvl-royal",
    regionId: "centre-val-de-loire",
    french: "royal",
    search: "royal",
    english: "royal",
    ipa: "/ʁwajal/",
    partOfSpeech: "adjective",
    gender: null,
    emoji: "👑",
    exampleFr: "Cette résidence royale date du seizième siècle.",
    exampleEn: "This royal residence dates from the sixteenth century.",
  },
  {
    id: "cvl-admirer",
    regionId: "centre-val-de-loire",
    french: "admirer",
    search: "admirer",
    english: "to admire",
    ipa: "/admiʁe/",
    partOfSpeech: "verb",
    gender: null,
    emoji: "👀",
    exampleFr: "Les visiteurs admirent les détails de la façade.",
    exampleEn: "The visitors admire the details of the façade.",
  },

  // Grand Est
  {
    id: "ges-marche-noel",
    regionId: "grand-est",
    french: "un marché de Noël",
    search: "marche de noel",
    english: "a Christmas market",
    ipa: "/œ̃ maʁʃe də nɔɛl/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🎄",
    exampleFr: "Le marché de Noël ouvre à la fin du mois.",
    exampleEn: "The Christmas market opens at the end of the month.",
  },
  {
    id: "ges-cathedrale",
    regionId: "grand-est",
    french: "une cathédrale",
    search: "cathedrale",
    english: "a cathedral",
    ipa: "/yn katedʁal/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "⛪",
    exampleFr: "La cathédrale possède de magnifiques vitraux.",
    exampleEn: "The cathedral has magnificent stained-glass windows.",
  },
  {
    id: "ges-cigogne",
    regionId: "grand-est",
    french: "une cigogne",
    search: "cigogne",
    english: "a stork",
    ipa: "/yn siɡɔɲ/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🪺",
    exampleFr: "Une cigogne construit son nid sur le toit.",
    exampleEn: "A stork is building its nest on the roof.",
  },
  {
    id: "ges-petillant",
    regionId: "grand-est",
    french: "pétillant",
    search: "petillant",
    english: "sparkling / fizzy",
    ipa: "/petijɑ̃/",
    partOfSpeech: "adjective",
    gender: null,
    emoji: "🫧",
    exampleFr: "Ce jus de pomme est légèrement pétillant.",
    exampleEn: "This apple juice is lightly sparkling.",
  },
  {
    id: "ges-celebrer",
    regionId: "grand-est",
    french: "célébrer",
    search: "celebrer",
    english: "to celebrate",
    ipa: "/selebʁe/",
    partOfSpeech: "verb",
    gender: null,
    emoji: "🎉",
    exampleFr: "Les habitants célèbrent le retour du printemps.",
    exampleEn: "The residents celebrate the return of spring.",
  },

  // Bourgogne-Franche-Comté
  {
    id: "bfc-vignoble",
    regionId: "bourgogne-franche-comte",
    french: "un vignoble",
    search: "vignoble",
    english: "a vineyard",
    ipa: "/œ̃ viɲɔbl/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🍇",
    exampleFr: "Le vignoble couvre les collines voisines.",
    exampleEn: "The vineyard covers the nearby hills.",
  },
  {
    id: "bfc-fromage",
    regionId: "bourgogne-franche-comte",
    french: "le fromage",
    search: "fromage",
    english: "cheese",
    ipa: "/lə fʁɔmaʒ/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🧀",
    exampleFr: "Ce fromage a un goût délicat.",
    exampleEn: "This cheese has a delicate flavour.",
  },
  {
    id: "bfc-tonneau",
    regionId: "bourgogne-franche-comte",
    french: "un tonneau",
    search: "tonneau",
    english: "a barrel",
    ipa: "/œ̃ tono/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🛢️",
    exampleFr: "Le vin vieillit dans un tonneau en bois.",
    exampleEn: "The wine ages in a wooden barrel.",
  },
  {
    id: "bfc-deguster",
    regionId: "bourgogne-franche-comte",
    french: "déguster",
    search: "deguster",
    english: "to taste / savour",
    ipa: "/deɡyste/",
    partOfSpeech: "verb",
    gender: null,
    emoji: "🍽️",
    exampleFr: "Nous dégustons une spécialité locale.",
    exampleEn: "We are tasting a local speciality.",
  },
  {
    id: "bfc-boise",
    regionId: "bourgogne-franche-comte",
    french: "boisé",
    search: "boise",
    english: "wooded",
    ipa: "/bwaze/",
    partOfSpeech: "adjective",
    gender: null,
    emoji: "🌲",
    exampleFr: "Le sentier est boisé et ombragé.",
    exampleEn: "The path is wooded and shaded.",
  },

  // Nouvelle-Aquitaine
  {
    id: "naq-dune",
    regionId: "nouvelle-aquitaine",
    french: "une dune",
    search: "dune",
    english: "a dune",
    ipa: "/yn dyn/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🏖️",
    exampleFr: "Nous montons au sommet de la dune.",
    exampleEn: "We are climbing to the top of the dune.",
  },
  {
    id: "naq-surf",
    regionId: "nouvelle-aquitaine",
    french: "le surf",
    search: "surf",
    english: "surfing",
    ipa: "/lə sœʁf/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🏄",
    exampleFr: "Il pratique le surf chaque été.",
    exampleEn: "He goes surfing every summer.",
  },
  {
    id: "naq-huitre",
    regionId: "nouvelle-aquitaine",
    french: "une huître",
    search: "huitre",
    english: "an oyster",
    ipa: "/yn ɥitʁ/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🦪",
    exampleFr: "Elle goûte une huître fraîche du bassin.",
    exampleEn: "She tastes a fresh oyster from the bay.",
  },
  {
    id: "naq-vaste",
    regionId: "nouvelle-aquitaine",
    french: "vaste",
    search: "vaste",
    english: "vast / spacious",
    ipa: "/vast/",
    partOfSpeech: "adjective",
    gender: null,
    emoji: "↔️",
    exampleFr: "La plage est vaste et presque vide.",
    exampleEn: "The beach is vast and almost empty.",
  },
  {
    id: "naq-recolter",
    regionId: "nouvelle-aquitaine",
    french: "récolter",
    search: "recolter",
    english: "to harvest",
    ipa: "/ʁekɔlte/",
    partOfSpeech: "verb",
    gender: null,
    emoji: "🧺",
    exampleFr: "On récolte le raisin au début de l'automne.",
    exampleEn: "The grapes are harvested at the beginning of autumn.",
  },

  // Auvergne-Rhône-Alpes
  {
    id: "ara-volcan",
    regionId: "auvergne-rhone-alpes",
    french: "un volcan",
    search: "volcan",
    english: "a volcano",
    ipa: "/œ̃ vɔlkɑ̃/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🌋",
    exampleFr: "Ce volcan est endormi depuis des milliers d'années.",
    exampleEn: "This volcano has been dormant for thousands of years.",
  },
  {
    id: "ara-sommet",
    regionId: "auvergne-rhone-alpes",
    french: "un sommet",
    search: "sommet",
    english: "a summit / peak",
    ipa: "/œ̃ sɔmɛ/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "⛰️",
    exampleFr: "Le sommet reste couvert de neige.",
    exampleEn: "The summit remains covered with snow.",
  },
  {
    id: "ara-neige",
    regionId: "auvergne-rhone-alpes",
    french: "la neige",
    search: "neige",
    english: "snow",
    ipa: "/la nɛʒ/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "❄️",
    exampleFr: "Dans les Alpes, la neige tombe tôt.",
    exampleEn: "In the Alps, snow falls early.",
  },
  {
    id: "ara-randonner",
    regionId: "auvergne-rhone-alpes",
    french: "randonner",
    search: "randonner",
    english: "to hike",
    ipa: "/ʁɑ̃dɔne/",
    partOfSpeech: "verb",
    gender: null,
    emoji: "🥾",
    exampleFr: "Nous aimons randonner autour du lac.",
    exampleEn: "We like hiking around the lake.",
  },
  {
    id: "ara-escarpe",
    regionId: "auvergne-rhone-alpes",
    french: "escarpé",
    search: "escarpe",
    english: "steep",
    ipa: "/ɛskaʁpe/",
    partOfSpeech: "adjective",
    gender: null,
    emoji: "📈",
    exampleFr: "Le chemin est escarpé mais bien balisé.",
    exampleEn: "The path is steep but well marked.",
  },

  // Occitanie
  {
    id: "occ-place",
    regionId: "occitanie",
    french: "une place",
    search: "place",
    english: "a square",
    ipa: "/yn plas/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "⛲",
    exampleFr: "La place accueille un marché le samedi.",
    exampleEn: "The square hosts a market on Saturdays.",
  },
  {
    id: "occ-canal",
    regionId: "occitanie",
    french: "le canal",
    search: "canal",
    english: "the canal",
    ipa: "/lə kanal/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🚲",
    exampleFr: "Des platanes bordent le canal.",
    exampleEn: "Plane trees line the canal.",
  },
  {
    id: "occ-brique",
    regionId: "occitanie",
    french: "la brique",
    search: "brique",
    english: "brick",
    ipa: "/la bʁik/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🧱",
    exampleFr: "De nombreuses maisons sont construites en brique rose.",
    exampleEn: "Many houses are built from pink brick.",
  },
  {
    id: "occ-ensoleille",
    regionId: "occitanie",
    french: "ensoleillé",
    search: "ensoleille",
    english: "sunny",
    ipa: "/ɑ̃sɔleje/",
    partOfSpeech: "adjective",
    gender: null,
    emoji: "☀️",
    exampleFr: "Le ciel reste ensoleillé toute la journée.",
    exampleEn: "The sky stays sunny all day.",
  },
  {
    id: "occ-flaner",
    regionId: "occitanie",
    french: "flâner",
    search: "flaner",
    english: "to stroll / wander",
    ipa: "/flɑne/",
    partOfSpeech: "verb",
    gender: null,
    emoji: "🚶",
    exampleFr: "Nous aimons flâner dans les petites rues.",
    exampleEn: "We like strolling through the small streets.",
  },

  // Provence-Alpes-Côte d'Azur
  {
    id: "paca-calanque",
    regionId: "provence-alpes-cote-d-azur",
    french: "une calanque",
    search: "calanque",
    english: "a rocky Mediterranean inlet",
    ipa: "/yn kalɑ̃k/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🏞️",
    exampleFr: "Un sentier descend vers une calanque tranquille.",
    exampleEn: "A path descends towards a quiet rocky inlet.",
  },
  {
    id: "paca-lavande",
    regionId: "provence-alpes-cote-d-azur",
    french: "la lavande",
    search: "lavande",
    english: "lavender",
    ipa: "/la lavɑ̃d/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🪻",
    exampleFr: "La lavande fleurit au début de l'été.",
    exampleEn: "Lavender blooms at the beginning of summer.",
  },
  {
    id: "paca-petanque",
    regionId: "provence-alpes-cote-d-azur",
    french: "la pétanque",
    search: "petanque",
    english: "pétanque",
    ipa: "/la petɑ̃k/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🔵",
    exampleFr: "Ils jouent à la pétanque sous les platanes.",
    exampleEn: "They play pétanque under the plane trees.",
  },
  {
    id: "paca-provencal",
    regionId: "provence-alpes-cote-d-azur",
    french: "provençal",
    search: "provencal",
    english: "Provençal",
    ipa: "/pʁɔvɑ̃sal/",
    partOfSpeech: "adjective",
    gender: null,
    emoji: "🧺",
    exampleFr: "Ce marché provençal vend des herbes parfumées.",
    exampleEn: "This Provençal market sells fragrant herbs.",
  },
  {
    id: "paca-se-baigner",
    regionId: "provence-alpes-cote-d-azur",
    french: "se baigner",
    search: "se baigner",
    english: "to swim / bathe",
    ipa: "/sə bɛɲe/",
    partOfSpeech: "pronominal verb",
    gender: null,
    emoji: "🏊",
    exampleFr: "On peut se baigner ici dès le mois de juin.",
    exampleEn: "You can swim here from June onwards.",
  },

  // Corse
  {
    id: "cor-ile",
    regionId: "corse",
    french: "une île",
    search: "ile",
    english: "an island",
    ipa: "/yn il/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🏝️",
    exampleFr: "La Corse est une île montagneuse de la Méditerranée.",
    exampleEn: "Corsica is a mountainous island in the Mediterranean.",
  },
  {
    id: "cor-maquis",
    regionId: "corse",
    french: "le maquis",
    search: "maquis",
    english: "Mediterranean scrubland",
    ipa: "/lə maki/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🌿",
    exampleFr: "Le maquis couvre une grande partie de la colline.",
    exampleEn: "The scrubland covers a large part of the hill.",
  },
  {
    id: "cor-village-perche",
    regionId: "corse",
    french: "un village perché",
    search: "village perche",
    english: "a hilltop village",
    ipa: "/œ̃ vilaʒ pɛʁʃe/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🏘️",
    exampleFr: "Un village perché domine la vallée.",
    exampleEn: "A hilltop village overlooks the valley.",
  },
  {
    id: "cor-sauvage",
    regionId: "corse",
    french: "sauvage",
    search: "sauvage",
    english: "wild / unspoilt",
    ipa: "/sovaʒ/",
    partOfSpeech: "adjective",
    gender: null,
    emoji: "🦅",
    exampleFr: "Cette plage reste sauvage et silencieuse.",
    exampleEn: "This beach remains unspoilt and quiet.",
  },
  {
    id: "cor-traverser",
    regionId: "corse",
    french: "traverser",
    search: "traverser",
    english: "to cross",
    ipa: "/tʁavɛʁse/",
    partOfSpeech: "verb",
    gender: null,
    emoji: "🥾",
    exampleFr: "Nous traversons la montagne par un ancien sentier.",
    exampleEn: "We cross the mountain on an old path.",
  },

  // Guadeloupe
  {
    id: "gua-archipel",
    regionId: "guadeloupe",
    french: "un archipel",
    search: "archipel",
    english: "an archipelago",
    ipa: "/œ̃n aʁʃipɛl/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🗺️",
    exampleFr: "La Guadeloupe est un archipel des Caraïbes.",
    exampleEn: "Guadeloupe is an archipelago in the Caribbean.",
  },
  {
    id: "gua-mangrove",
    regionId: "guadeloupe",
    french: "la mangrove",
    search: "mangrove",
    english: "the mangrove forest",
    ipa: "/la mɑ̃ɡʁɔv/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🌿",
    exampleFr: "La mangrove protège la côte et abrite des oiseaux.",
    exampleEn: "The mangrove protects the coast and shelters birds.",
  },
  {
    id: "gua-colibri",
    regionId: "guadeloupe",
    french: "un colibri",
    search: "colibri",
    english: "a hummingbird",
    ipa: "/œ̃ kɔlibʁi/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🐦",
    exampleFr: "Un colibri se pose près d'une fleur rouge.",
    exampleEn: "A hummingbird lands near a red flower.",
  },
  {
    id: "gua-creole",
    regionId: "guadeloupe",
    french: "le créole",
    search: "creole",
    english: "Creole language",
    ipa: "/lə kʁeɔl/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "💬",
    exampleFr: "Le créole guadeloupéen est parlé aux côtés du français.",
    exampleEn: "Guadeloupean Creole is spoken alongside French.",
  },
  {
    id: "gua-epice",
    regionId: "guadeloupe",
    french: "épicé",
    search: "epice",
    english: "spicy / seasoned",
    ipa: "/epise/",
    partOfSpeech: "adjective",
    gender: null,
    emoji: "🌶️",
    exampleFr: "Cette sauce est douce et légèrement épicée.",
    exampleEn: "This sauce is mild and lightly spiced.",
  },

  // Martinique
  {
    id: "mar-yole",
    regionId: "martinique",
    french: "une yole",
    search: "yole",
    english: "a traditional sailing boat",
    ipa: "/yn jɔl/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "⛵",
    exampleFr: "La yole avance rapidement grâce au vent.",
    exampleEn: "The yole moves quickly thanks to the wind.",
  },
  {
    id: "mar-canne-sucre",
    regionId: "martinique",
    french: "la canne à sucre",
    search: "canne a sucre",
    english: "sugar cane",
    ipa: "/la kan a sykʁ/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🌾",
    exampleFr: "La canne à sucre pousse sous le soleil tropical.",
    exampleEn: "Sugar cane grows under the tropical sun.",
  },
  {
    id: "mar-jardin-tropical",
    regionId: "martinique",
    french: "un jardin tropical",
    search: "jardin tropical",
    english: "a tropical garden",
    ipa: "/œ̃ ʒaʁdɛ̃ tʁɔpikal/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🌺",
    exampleFr: "Le jardin tropical rassemble des plantes colorées.",
    exampleEn: "The tropical garden brings together colourful plants.",
  },
  {
    id: "mar-ramer",
    regionId: "martinique",
    french: "ramer",
    search: "ramer",
    english: "to row",
    ipa: "/ʁame/",
    partOfSpeech: "verb",
    gender: null,
    emoji: "🚣",
    exampleFr: "L'équipe doit ramer au même rythme.",
    exampleEn: "The team must row at the same pace.",
  },
  {
    id: "mar-fleuri",
    regionId: "martinique",
    french: "fleuri",
    search: "fleuri",
    english: "flower-filled / in bloom",
    ipa: "/flœʁi/",
    partOfSpeech: "adjective",
    gender: null,
    emoji: "🌸",
    exampleFr: "Le chemin fleuri traverse le village.",
    exampleEn: "The flower-lined path crosses the village.",
  },

  // Guyane
  {
    id: "guy-foret-tropicale",
    regionId: "guyane",
    french: "la forêt tropicale",
    search: "foret tropicale",
    english: "the tropical rainforest",
    ipa: "/la fɔʁɛ tʁɔpikal/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🌳",
    exampleFr: "La forêt tropicale couvre une grande partie de la Guyane.",
    exampleEn: "The tropical rainforest covers a large part of French Guiana.",
  },
  {
    id: "guy-fleuve",
    regionId: "guyane",
    french: "un fleuve",
    search: "fleuve",
    english: "a river that flows to the sea",
    ipa: "/œ̃ flœv/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🛶",
    exampleFr: "Le fleuve sert de voie de transport entre les villages.",
    exampleEn: "The river serves as a transport route between villages.",
  },
  {
    id: "guy-centre-spatial",
    regionId: "guyane",
    french: "le centre spatial",
    search: "centre spatial",
    english: "the space centre",
    ipa: "/lə sɑ̃tʁ spasjal/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🛰️",
    exampleFr: "Le centre spatial se trouve près de Kourou.",
    exampleEn: "The space centre is located near Kourou.",
  },
  {
    id: "guy-decoller",
    regionId: "guyane",
    french: "décoller",
    search: "decoller",
    english: "to take off",
    ipa: "/dekɔle/",
    partOfSpeech: "verb",
    gender: null,
    emoji: "🚀",
    exampleFr: "La fusée va décoller dans quelques minutes.",
    exampleEn: "The rocket is going to take off in a few minutes.",
  },
  {
    id: "guy-immense",
    regionId: "guyane",
    french: "immense",
    search: "immense",
    english: "immense / vast",
    ipa: "/imɑ̃s/",
    partOfSpeech: "adjective",
    gender: null,
    emoji: "🌎",
    exampleFr: "Depuis le bateau, la forêt semble immense.",
    exampleEn: "From the boat, the forest seems immense.",
  },

  // La Réunion
  {
    id: "reu-cirque",
    regionId: "la-reunion",
    french: "un cirque",
    search: "cirque",
    english: "a natural mountain amphitheatre",
    ipa: "/œ̃ siʁk/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🏞️",
    exampleFr: "Le cirque de Mafate est entouré de hautes montagnes.",
    exampleEn: "The Cirque de Mafate is surrounded by high mountains.",
  },
  {
    id: "reu-piton",
    regionId: "la-reunion",
    french: "un piton",
    search: "piton",
    english: "a sharp peak",
    ipa: "/œ̃ pitɔ̃/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🌋",
    exampleFr: "Un nuage cache le sommet du piton.",
    exampleEn: "A cloud hides the summit of the peak.",
  },
  {
    id: "reu-cascade",
    regionId: "la-reunion",
    french: "une cascade",
    search: "cascade",
    english: "a waterfall",
    ipa: "/yn kaskad/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "💧",
    exampleFr: "La cascade tombe dans un bassin naturel.",
    exampleEn: "The waterfall drops into a natural pool.",
  },
  {
    id: "reu-gravir",
    regionId: "la-reunion",
    french: "gravir",
    search: "gravir",
    english: "to climb",
    ipa: "/ɡʁaviʁ/",
    partOfSpeech: "verb",
    gender: null,
    emoji: "🧗",
    exampleFr: "Nous partons tôt pour gravir le volcan.",
    exampleEn: "We leave early to climb the volcano.",
  },
  {
    id: "reu-volcanique",
    regionId: "la-reunion",
    french: "volcanique",
    search: "volcanique",
    english: "volcanic",
    ipa: "/vɔlkanik/",
    partOfSpeech: "adjective",
    gender: null,
    emoji: "🪨",
    exampleFr: "Le paysage volcanique change après chaque éruption.",
    exampleEn: "The volcanic landscape changes after each eruption.",
  },

  // Mayotte
  {
    id: "may-lagon",
    regionId: "mayotte",
    french: "un lagon",
    search: "lagon",
    english: "a lagoon",
    ipa: "/œ̃ laɡɔ̃/",
    partOfSpeech: "noun",
    gender: "masculine",
    emoji: "🌊",
    exampleFr: "Le lagon abrite une grande diversité de poissons.",
    exampleEn: "The lagoon is home to a wide variety of fish.",
  },
  {
    id: "may-tortue-marine",
    regionId: "mayotte",
    french: "une tortue marine",
    search: "tortue marine",
    english: "a sea turtle",
    ipa: "/yn tɔʁty maʁin/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🐢",
    exampleFr: "Une tortue marine nage près de la plage.",
    exampleEn: "A sea turtle swims near the beach.",
  },
  {
    id: "may-barriere-corail",
    regionId: "mayotte",
    french: "une barrière de corail",
    search: "barriere de corail",
    english: "a coral reef barrier",
    ipa: "/yn baʁjɛʁ də kɔʁaj/",
    partOfSpeech: "noun",
    gender: "feminine",
    emoji: "🪸",
    exampleFr: "Une barrière de corail entoure une grande partie du lagon.",
    exampleEn: "A coral reef barrier surrounds much of the lagoon.",
  },
  {
    id: "may-pagayer",
    regionId: "mayotte",
    french: "pagayer",
    search: "pagayer",
    english: "to paddle",
    ipa: "/paɡeje/",
    partOfSpeech: "verb",
    gender: null,
    emoji: "🛶",
    exampleFr: "Nous allons pagayer calmement dans le lagon.",
    exampleEn: "We are going to paddle calmly in the lagoon.",
  },
  {
    id: "may-preserve",
    regionId: "mayotte",
    french: "préservé",
    search: "preserve",
    english: "protected / unspoilt",
    ipa: "/pʁezeʁve/",
    partOfSpeech: "adjective",
    gender: null,
    emoji: "🛡️",
    exampleFr: "Cet espace naturel est fragile et préservé.",
    exampleEn: "This natural area is fragile and protected.",
  },
] as const satisfies readonly FoundationWord[];

type CurriculumEntry = readonly [
  id: string,
  regionId: RegionId,
  lesson: CurriculumLessonNumber,
  french: string,
  search: string,
  english: string,
  ipa: string,
  partOfSpeech: PartOfSpeech,
  gender: GrammaticalGender | null,
  emoji: string,
  exampleFr: string,
  exampleEn: string,
];

const CURRICULUM_EXPANSION = [
  // Île-de-France — lessons 2 and 3
  ["idf-station", "ile-de-france", 2, "une station", "station", "a station", "/yn stasjɔ̃/", "noun", "feminine", "🚉", "Cette station a deux sorties.", "This station has two exits."],
  ["idf-billet", "ile-de-france", 2, "un billet", "billet", "a ticket", "/œ̃ bijɛ/", "noun", "masculine", "🎫", "J'achète un billet au guichet.", "I am buying a ticket at the ticket window."],
  ["idf-correspondance", "ile-de-france", 2, "une correspondance", "correspondance", "a transfer / connection", "/yn kɔʁɛspɔ̃dɑ̃s/", "noun", "feminine", "🔁", "Nous avons une correspondance à Châtelet.", "We have a transfer at Châtelet."],
  ["idf-valider", "ile-de-france", 2, "valider", "valider", "to validate", "/valide/", "verb", null, "✅", "Validez votre billet avant de monter.", "Validate your ticket before boarding."],
  ["idf-prochain", "ile-de-france", 2, "prochain", "prochain", "next", "/pʁɔʃɛ̃/", "adjective", null, "➡️", "Le prochain train arrive dans cinq minutes.", "The next train arrives in five minutes."],
  ["idf-quartier", "ile-de-france", 3, "un quartier", "quartier", "a neighbourhood", "/œ̃ kaʁtje/", "noun", "masculine", "🏘️", "Ce quartier est calme le matin.", "This neighbourhood is quiet in the morning."],
  ["idf-boulangerie", "ile-de-france", 3, "une boulangerie", "boulangerie", "a bakery", "/yn bulɑ̃ʒʁi/", "noun", "feminine", "🥖", "La boulangerie ouvre à sept heures.", "The bakery opens at seven o'clock."],
  ["idf-terrasse", "ile-de-france", 3, "une terrasse", "terrasse", "a café terrace", "/yn tɛʁas/", "noun", "feminine", "☕", "On boit un café en terrasse.", "We have a coffee outside on the terrace."],
  ["idf-louer", "ile-de-france", 3, "louer", "louer", "to rent", "/lwe/", "verb", null, "🔑", "Ils veulent louer un petit appartement.", "They want to rent a small apartment."],
  ["idf-bonde", "ile-de-france", 3, "bondé", "bonde", "crowded", "/bɔ̃de/", "adjective", null, "👥", "Le bus est bondé aux heures de pointe.", "The bus is crowded during rush hour."],

  // Hauts-de-France — lessons 2 and 3
  ["hdf-etal", "hauts-de-france", 2, "un étal", "etal", "a market stall", "/œ̃n etal/", "noun", "masculine", "🥬", "Le marchand range ses légumes sur l'étal.", "The vendor arranges his vegetables on the stall."],
  ["hdf-moules", "hauts-de-france", 2, "les moules", "moules", "mussels", "/le mul/", "noun", "feminine", "🦪", "Nous partageons des moules au déjeuner.", "We share mussels at lunch."],
  ["hdf-frites", "hauts-de-france", 2, "les frites", "frites", "fries", "/le fʁit/", "noun", "feminine", "🍟", "Les frites sont dorées et croustillantes.", "The fries are golden and crisp."],
  ["hdf-gouter", "hauts-de-france", 2, "goûter", "gouter", "to taste / try", "/ɡute/", "verb", null, "🥄", "Voulez-vous goûter cette spécialité ?", "Would you like to try this speciality?"],
  ["hdf-bon-marche", "hauts-de-france", 2, "bon marché", "bon marche", "inexpensive", "/bɔ̃ maʁʃe/", "adjective", null, "🏷️", "Ce sac est joli et bon marché.", "This bag is pretty and inexpensive."],
  ["hdf-mairie", "hauts-de-france", 3, "une mairie", "mairie", "a town hall", "/yn mɛʁi/", "noun", "feminine", "🏛️", "La mairie se trouve près du parc.", "The town hall is near the park."],
  ["hdf-grand-place", "hauts-de-france", 3, "la Grand-Place", "grand place", "the main square", "/la ɡʁɑ̃ plas/", "noun", "feminine", "⛲", "La Grand-Place est pleine de monde.", "The main square is full of people."],
  ["hdf-pluie", "hauts-de-france", 3, "la pluie", "pluie", "the rain", "/la plɥi/", "noun", "feminine", "🌧️", "La pluie commence après midi.", "The rain starts in the afternoon."],
  ["hdf-se-promener", "hauts-de-france", 3, "se promener", "se promener", "to take a walk", "/sə pʁɔmne/", "pronominal verb", null, "🚶", "Nous aimons nous promener dans les vieilles rues.", "We like taking a walk through the old streets."],
  ["hdf-venteux", "hauts-de-france", 3, "venteux", "venteux", "windy", "/vɑ̃tø/", "adjective", null, "💨", "Le bord de mer est venteux aujourd'hui.", "The seafront is windy today."],

  // Normandie — lessons 2 and 3
  ["nor-verger", "normandie", 2, "un verger", "verger", "an orchard", "/œ̃ vɛʁʒe/", "noun", "masculine", "🌳", "Le verger produit beaucoup de pommes.", "The orchard produces many apples."],
  ["nor-pomme", "normandie", 2, "une pomme", "pomme", "an apple", "/yn pɔm/", "noun", "feminine", "🍎", "Cette pomme est douce et croquante.", "This apple is sweet and crisp."],
  ["nor-beurre", "normandie", 2, "le beurre", "beurre", "butter", "/lə bœʁ/", "noun", "masculine", "🧈", "Elle met du beurre sur son pain.", "She puts butter on her bread."],
  ["nor-camembert", "normandie", 2, "le camembert", "camembert", "Camembert cheese", "/lə kamɑ̃bɛʁ/", "noun", "masculine", "🧀", "Le camembert est servi à température ambiante.", "Camembert is served at room temperature."],
  ["nor-fabriquer", "normandie", 2, "fabriquer", "fabriquer", "to make / manufacture", "/fabʁike/", "verb", null, "🧑‍🍳", "Cette ferme fabrique du fromage.", "This farm makes cheese."],
  ["nor-port", "normandie", 3, "un port", "port", "a harbour", "/œ̃ pɔʁ/", "noun", "masculine", "⚓", "Les bateaux rentrent au port avant la nuit.", "The boats return to the harbour before nightfall."],
  ["nor-plage", "normandie", 3, "une plage", "plage", "a beach", "/yn plaʒ/", "noun", "feminine", "🏖️", "Nous marchons sur la plage à marée basse.", "We walk on the beach at low tide."],
  ["nor-parapluie", "normandie", 3, "un parapluie", "parapluie", "an umbrella", "/œ̃ paʁaplɥi/", "noun", "masculine", "☂️", "N'oublie pas ton parapluie ce matin.", "Do not forget your umbrella this morning."],
  ["nor-pleuvoir", "normandie", 3, "pleuvoir", "pleuvoir", "to rain", "/pløvwaʁ/", "verb", null, "🌦️", "Il va pleuvoir près de la côte.", "It is going to rain near the coast."],
  ["nor-humide", "normandie", 3, "humide", "humide", "damp / humid", "/ymid/", "adjective", null, "💧", "L'air est frais et humide.", "The air is cool and damp."],

  // Bretagne — lessons 2 and 3
  ["bre-port-de-peche", "bretagne", 2, "un port de pêche", "port de peche", "a fishing harbour", "/œ̃ pɔʁ də pɛʃ/", "noun", "masculine", "⚓", "Le port de pêche s'anime tôt le matin.", "The fishing harbour comes alive early in the morning."],
  ["bre-bateau", "bretagne", 2, "un bateau", "bateau", "a boat", "/œ̃ bato/", "noun", "masculine", "⛵", "Ce bateau quitte le quai à neuf heures.", "This boat leaves the quay at nine o'clock."],
  ["bre-vague", "bretagne", 2, "une vague", "vague", "a wave", "/yn vaɡ/", "noun", "feminine", "🌊", "Une grande vague frappe les rochers.", "A large wave hits the rocks."],
  ["bre-embarquer", "bretagne", 2, "embarquer", "embarquer", "to board", "/ɑ̃baʁke/", "verb", null, "🛳️", "Les passagers vont embarquer dans quelques minutes.", "The passengers are going to board in a few minutes."],
  ["bre-marin", "bretagne", 2, "marin", "marin", "maritime / sea", "/maʁɛ̃/", "adjective", null, "🌬️", "L'air marin ouvre l'appétit.", "The sea air makes you hungry."],
  ["bre-galette", "bretagne", 3, "une galette", "galette", "a buckwheat pancake", "/yn ɡalɛt/", "noun", "feminine", "🥞", "Je choisis une galette au fromage.", "I choose a buckwheat pancake with cheese."],
  ["bre-beurre-sale", "bretagne", 3, "le beurre salé", "beurre sale", "salted butter", "/lə bœʁ sale/", "noun", "masculine", "🧈", "Le beurre salé fond sur la crêpe chaude.", "The salted butter melts on the warm crêpe."],
  ["bre-bolee-cidre", "bretagne", 3, "une bolée de cidre", "bolee de cidre", "a small bowl of cider", "/yn bɔle də sidʁ/", "noun", "feminine", "🍎", "Il commande une bolée de cidre.", "He orders a small bowl of cider."],
  ["bre-commander", "bretagne", 3, "commander", "commander", "to order", "/kɔmɑ̃de/", "verb", null, "📝", "Nous allons commander le plat du jour.", "We are going to order the dish of the day."],
  ["bre-delicieux", "bretagne", 3, "délicieux", "delicieux", "delicious", "/delisjø/", "adjective", null, "😋", "Ce caramel est vraiment délicieux.", "This caramel is truly delicious."],

  // Pays de la Loire — lessons 2 and 3
  ["pdl-quai", "pays-de-la-loire", 2, "un quai", "quai", "a quay / platform", "/œ̃ kɛ/", "noun", "masculine", "🛟", "Nous attendons le bateau sur le quai.", "We wait for the boat on the quay."],
  ["pdl-tramway", "pays-de-la-loire", 2, "le tramway", "tramway", "the tram", "/lə tʁamwɛ/", "noun", "masculine", "🚊", "Le tramway traverse le centre de Nantes.", "The tram crosses the centre of Nantes."],
  ["pdl-plage-sable", "pays-de-la-loire", 2, "une plage de sable", "plage de sable", "a sandy beach", "/yn plaʒ də sabl/", "noun", "feminine", "🏖️", "Les enfants jouent sur la plage de sable.", "The children play on the sandy beach."],
  ["pdl-prendre", "pays-de-la-loire", 2, "prendre", "prendre", "to take", "/pʁɑ̃dʁ/", "verb", null, "🚌", "Nous prenons le tram pour aller au centre.", "We take the tram to go downtown."],
  ["pdl-dynamique", "pays-de-la-loire", 2, "dynamique", "dynamique", "lively / dynamic", "/dinamik/", "adjective", null, "⚡", "Nantes est une ville jeune et dynamique.", "Nantes is a young and dynamic city."],
  ["pdl-velo", "pays-de-la-loire", 3, "un vélo", "velo", "a bicycle", "/œ̃ velo/", "noun", "masculine", "🚲", "Je loue un vélo pour la journée.", "I rent a bicycle for the day."],
  ["pdl-pique-nique", "pays-de-la-loire", 3, "un pique-nique", "pique nique", "a picnic", "/œ̃ piknik/", "noun", "masculine", "🧺", "Nous préparons un pique-nique au bord de l'eau.", "We prepare a picnic by the water."],
  ["pdl-oiseau", "pays-de-la-loire", 3, "un oiseau", "oiseau", "a bird", "/œ̃n wazo/", "noun", "masculine", "🐦", "Un oiseau se pose dans les roseaux.", "A bird lands among the reeds."],
  ["pdl-observer", "pays-de-la-loire", 3, "observer", "observer", "to observe / watch", "/ɔpsɛʁve/", "verb", null, "🔭", "On peut observer les oiseaux du marais.", "You can watch the birds in the marsh."],
  ["pdl-local", "pays-de-la-loire", 3, "local", "local", "local", "/lɔkal/", "adjective", null, "📍", "Nous achetons des produits locaux.", "We buy local products."],

  // Centre-Val de Loire — lessons 2 and 3
  ["cvl-entree", "centre-val-de-loire", 2, "une entrée", "entree", "an entrance / admission", "/yn ɑ̃tʁe/", "noun", "feminine", "🎟️", "L'entrée du château ferme à dix-sept heures.", "The castle entrance closes at five p.m."],
  ["cvl-visite-guidee", "centre-val-de-loire", 2, "une visite guidée", "visite guidee", "a guided tour", "/yn vizit ɡide/", "noun", "feminine", "🗣️", "La visite guidée dure une heure.", "The guided tour lasts one hour."],
  ["cvl-escalier", "centre-val-de-loire", 2, "un escalier", "escalier", "a staircase", "/œ̃n ɛskalje/", "noun", "masculine", "🪜", "Cet escalier mène à la grande salle.", "This staircase leads to the great hall."],
  ["cvl-reserver", "centre-val-de-loire", 2, "réserver", "reserver", "to book / reserve", "/ʁezeʁve/", "verb", null, "📅", "Il vaut mieux réserver les billets en ligne.", "It is better to book the tickets online."],
  ["cvl-ancien", "centre-val-de-loire", 2, "ancien", "ancien", "old / ancient", "/ɑ̃sjɛ̃/", "adjective", null, "🏺", "Nous visitons une ancienne demeure royale.", "We are visiting an old royal residence."],
  ["cvl-riviere", "centre-val-de-loire", 3, "une rivière", "riviere", "a river", "/yn ʁivjɛʁ/", "noun", "feminine", "🏞️", "Une petite rivière traverse le village.", "A small river runs through the village."],
  ["cvl-pont", "centre-val-de-loire", 3, "un pont", "pont", "a bridge", "/œ̃ pɔ̃/", "noun", "masculine", "🌉", "Le pont offre une belle vue sur la Loire.", "The bridge offers a beautiful view of the Loire."],
  ["cvl-foret", "centre-val-de-loire", 3, "une forêt", "foret", "a forest", "/yn fɔʁɛ/", "noun", "feminine", "🌲", "Nous traversons une forêt de chênes.", "We cross an oak forest."],
  ["cvl-longer", "centre-val-de-loire", 3, "longer", "longer", "to follow / run alongside", "/lɔ̃ʒe/", "verb", null, "🚶", "Le chemin longe la rivière.", "The path follows the river."],
  ["cvl-tranquille", "centre-val-de-loire", 3, "tranquille", "tranquille", "quiet / peaceful", "/tʁɑ̃kil/", "adjective", null, "🍃", "La campagne est tranquille au printemps.", "The countryside is peaceful in spring."],

  // Grand Est — lessons 2 and 3
  ["ges-frontiere", "grand-est", 2, "une frontière", "frontiere", "a border", "/yn fʁɔ̃tjɛʁ/", "noun", "feminine", "🗺️", "La frontière est à quelques kilomètres.", "The border is a few kilometres away."],
  ["ges-gare", "grand-est", 2, "une gare", "gare", "a train station", "/yn ɡaʁ/", "noun", "feminine", "🚆", "La gare se trouve derrière la cathédrale.", "The train station is behind the cathedral."],
  ["ges-tram", "grand-est", 2, "le tram", "tram", "the tram", "/lə tʁam/", "noun", "masculine", "🚋", "Le tram arrive toutes les dix minutes.", "The tram arrives every ten minutes."],
  ["ges-changer", "grand-est", 2, "changer", "changer", "to change", "/ʃɑ̃ʒe/", "verb", null, "🔄", "Vous devez changer de train à Strasbourg.", "You must change trains in Strasbourg."],
  ["ges-voisin", "grand-est", 2, "voisin", "voisin", "neighbouring", "/vwazɛ̃/", "adjective", null, "🤝", "Nous visitons une ville voisine demain.", "We are visiting a neighbouring town tomorrow."],
  ["ges-pain-epices", "grand-est", 3, "le pain d'épices", "pain d epices", "gingerbread", "/lə pɛ̃ depis/", "noun", "masculine", "🍞", "Le pain d'épices sent la cannelle.", "The gingerbread smells of cinnamon."],
  ["ges-choucroute", "grand-est", 3, "la choucroute", "choucroute", "sauerkraut / choucroute", "/la ʃukʁut/", "noun", "feminine", "🥘", "La choucroute est un plat généreux.", "Choucroute is a hearty dish."],
  ["ges-poterie", "grand-est", 3, "une poterie", "poterie", "a piece of pottery", "/yn pɔtʁi/", "noun", "feminine", "🏺", "Cette poterie est peinte à la main.", "This piece of pottery is painted by hand."],
  ["ges-decorer", "grand-est", 3, "décorer", "decorer", "to decorate", "/dekɔʁe/", "verb", null, "🎨", "Les habitants décorent les fenêtres pour Noël.", "The residents decorate the windows for Christmas."],
  ["ges-traditionnel", "grand-est", 3, "traditionnel", "traditionnel", "traditional", "/tʁadisjɔnɛl/", "adjective", null, "🧵", "Nous découvrons un savoir-faire traditionnel.", "We discover a traditional craft."],

  // Bourgogne-Franche-Comté — lessons 2 and 3
  ["bfc-cave", "bourgogne-franche-comte", 2, "une cave", "cave", "a cellar", "/yn kav/", "noun", "feminine", "🪨", "La cave reste fraîche toute l'année.", "The cellar stays cool all year."],
  ["bfc-bouteille", "bourgogne-franche-comte", 2, "une bouteille", "bouteille", "a bottle", "/yn butɛj/", "noun", "feminine", "🍾", "Cette bouteille vient d'un domaine voisin.", "This bottle comes from a nearby estate."],
  ["bfc-recette", "bourgogne-franche-comte", 2, "une recette", "recette", "a recipe", "/yn ʁəsɛt/", "noun", "feminine", "📖", "Ma grand-mère garde sa recette dans un carnet.", "My grandmother keeps her recipe in a notebook."],
  ["bfc-servir", "bourgogne-franche-comte", 2, "servir", "servir", "to serve", "/sɛʁviʁ/", "verb", null, "🍽️", "On sert le fromage après le plat principal.", "Cheese is served after the main course."],
  ["bfc-savoureux", "bourgogne-franche-comte", 2, "savoureux", "savoureux", "flavourful", "/savuʁø/", "adjective", null, "😋", "Ce plat simple est très savoureux.", "This simple dish is very flavourful."],
  ["bfc-clocher", "bourgogne-franche-comte", 3, "un clocher", "clocher", "a church tower", "/œ̃ klɔʃe/", "noun", "masculine", "⛪", "Le clocher est visible depuis les vignes.", "The church tower is visible from the vineyards."],
  ["bfc-foret-sapins", "bourgogne-franche-comte", 3, "une forêt de sapins", "foret de sapins", "a fir forest", "/yn fɔʁɛ də sapɛ̃/", "noun", "feminine", "🌲", "Le sentier entre dans une forêt de sapins.", "The path enters a fir forest."],
  ["bfc-atelier", "bourgogne-franche-comte", 3, "un atelier", "atelier", "a workshop", "/œ̃n atəlje/", "noun", "masculine", "🛠️", "L'artisan nous accueille dans son atelier.", "The craftsperson welcomes us into the workshop."],
  ["bfc-faconner", "bourgogne-franche-comte", 3, "façonner", "faconner", "to shape / craft", "/fasɔne/", "verb", null, "👐", "Elle façonne un bol en argile.", "She shapes a bowl from clay."],
  ["bfc-medieval", "bourgogne-franche-comte", 3, "médiéval", "medieval", "medieval", "/medjeval/", "adjective", null, "🏰", "Le village conserve un pont médiéval.", "The village has preserved a medieval bridge."],

  // Nouvelle-Aquitaine — lessons 2 and 3
  ["naq-marche-couvert", "nouvelle-aquitaine", 2, "un marché couvert", "marche couvert", "an indoor market", "/œ̃ maʁʃe kuvɛʁ/", "noun", "masculine", "🧺", "Le marché couvert ouvre tôt le samedi.", "The indoor market opens early on Saturday."],
  ["naq-raisin", "nouvelle-aquitaine", 2, "le raisin", "raisin", "grapes", "/lə ʁɛzɛ̃/", "noun", "masculine", "🍇", "Le raisin est prêt pour la récolte.", "The grapes are ready for harvest."],
  ["naq-panier", "nouvelle-aquitaine", 2, "un panier", "panier", "a basket", "/œ̃ pɑnje/", "noun", "masculine", "🧺", "Elle remplit son panier de fruits frais.", "She fills her basket with fresh fruit."],
  ["naq-acheter", "nouvelle-aquitaine", 2, "acheter", "acheter", "to buy", "/aʃte/", "verb", null, "🛍️", "Je vais acheter des tomates au marché.", "I am going to buy tomatoes at the market."],
  ["naq-mur", "nouvelle-aquitaine", 2, "mûr", "mur", "ripe", "/myʁ/", "adjective", null, "🍑", "Ce melon est enfin mûr.", "This melon is finally ripe."],
  ["naq-piste-cyclable", "nouvelle-aquitaine", 3, "une piste cyclable", "piste cyclable", "a cycle path", "/yn pist siklabl/", "noun", "feminine", "🚲", "La piste cyclable longe l'océan.", "The cycle path runs along the ocean."],
  ["naq-pinede", "nouvelle-aquitaine", 3, "une pinède", "pinede", "a pine grove", "/yn pinɛd/", "noun", "feminine", "🌲", "Nous faisons une pause dans la pinède.", "We take a break in the pine grove."],
  ["naq-lac", "nouvelle-aquitaine", 3, "un lac", "lac", "a lake", "/œ̃ lak/", "noun", "masculine", "🏞️", "Le lac est calme avant le coucher du soleil.", "The lake is calm before sunset."],
  ["naq-pedaler", "nouvelle-aquitaine", 3, "pédaler", "pedaler", "to pedal / cycle", "/pedale/", "verb", null, "🚴", "Nous pédalons sous les pins.", "We cycle beneath the pine trees."],
  ["naq-ombrage", "nouvelle-aquitaine", 3, "ombragé", "ombrage", "shaded", "/ɔ̃bʁaʒe/", "adjective", null, "🌳", "Le chemin est ombragé et agréable.", "The path is shaded and pleasant."],

  // Auvergne-Rhône-Alpes — lessons 2 and 3
  ["ara-chalet", "auvergne-rhone-alpes", 2, "un chalet", "chalet", "a chalet", "/œ̃ ʃalɛ/", "noun", "masculine", "🏡", "Notre chalet donne sur la montagne.", "Our chalet overlooks the mountain."],
  ["ara-echarpe", "auvergne-rhone-alpes", 2, "une écharpe", "echarpe", "a scarf", "/yn eʃaʁp/", "noun", "feminine", "🧣", "Mets une écharpe avant de sortir.", "Put on a scarf before going outside."],
  ["ara-chaussures-randonnee", "auvergne-rhone-alpes", 2, "les chaussures de randonnée", "chaussures de randonnee", "hiking boots", "/le ʃosyʁ də ʁɑ̃dɔne/", "noun", "feminine", "🥾", "Mes chaussures de randonnée sont imperméables.", "My hiking boots are waterproof."],
  ["ara-neiger", "auvergne-rhone-alpes", 2, "neiger", "neiger", "to snow", "/nɛʒe/", "verb", null, "🌨️", "Il commence à neiger au-dessus du village.", "It is starting to snow above the village."],
  ["ara-chaud", "auvergne-rhone-alpes", 2, "chaud", "chaud", "warm / hot", "/ʃo/", "adjective", null, "🔥", "Prenez une boisson chaude après la marche.", "Have a warm drink after the walk."],
  ["ara-telepherique", "auvergne-rhone-alpes", 3, "le téléphérique", "telepherique", "the cable car", "/lə telefeʁik/", "noun", "masculine", "🚠", "Le téléphérique monte jusqu'au sommet.", "The cable car goes up to the summit."],
  ["ara-lac-montagne", "auvergne-rhone-alpes", 3, "un lac de montagne", "lac de montagne", "a mountain lake", "/œ̃ lak də mɔ̃taɲ/", "noun", "masculine", "🏞️", "Un lac de montagne apparaît derrière le col.", "A mountain lake appears beyond the pass."],
  ["ara-refuge", "auvergne-rhone-alpes", 3, "un refuge", "refuge", "a mountain hut", "/œ̃ ʁəfyʒ/", "noun", "masculine", "🛖", "Le refuge sert un repas chaud le soir.", "The mountain hut serves a hot meal in the evening."],
  ["ara-skier", "auvergne-rhone-alpes", 3, "skier", "skier", "to ski", "/skije/", "verb", null, "⛷️", "Elle apprend à skier sur une piste facile.", "She is learning to ski on an easy slope."],
  ["ara-prudent", "auvergne-rhone-alpes", 3, "prudent", "prudent", "careful", "/pʁydɑ̃/", "adjective", null, "⚠️", "Soyez prudent quand le sentier est gelé.", "Be careful when the path is icy."],

  // Occitanie — lessons 2 and 3
  ["occ-peniche", "occitanie", 2, "une péniche", "peniche", "a canal boat", "/yn peniʃ/", "noun", "feminine", "🛥️", "Une péniche avance lentement sur le canal.", "A canal boat moves slowly along the canal."],
  ["occ-ecluse", "occitanie", 2, "une écluse", "ecluse", "a lock", "/yn eklyz/", "noun", "feminine", "🚧", "La péniche entre dans l'écluse.", "The canal boat enters the lock."],
  ["occ-chemin-halage", "occitanie", 2, "un chemin de halage", "chemin de halage", "a towpath", "/œ̃ ʃəmɛ̃ də alaʒ/", "noun", "masculine", "🚶", "Le chemin de halage suit le canal.", "The towpath follows the canal."],
  ["occ-suivre", "occitanie", 2, "suivre", "suivre", "to follow", "/sɥivʁ/", "verb", null, "➡️", "Suivez le canal jusqu'au prochain pont.", "Follow the canal to the next bridge."],
  ["occ-lent", "occitanie", 2, "lent", "lent", "slow", "/lɑ̃/", "adjective", null, "🐢", "Le rythme est lent et reposant.", "The pace is slow and relaxing."],
  ["occ-marche-plein-air", "occitanie", 3, "un marché en plein air", "marche en plein air", "an open-air market", "/œ̃ maʁʃe ɑ̃ plɛ̃n ɛʁ/", "noun", "masculine", "🧺", "Le marché en plein air occupe toute la place.", "The open-air market fills the whole square."],
  ["occ-abricot", "occitanie", 3, "un abricot", "abricot", "an apricot", "/œ̃n abʁiko/", "noun", "masculine", "🍑", "Cet abricot est doux et juteux.", "This apricot is sweet and juicy."],
  ["occ-olive", "occitanie", 3, "une olive", "olive", "an olive", "/yn ɔliv/", "noun", "feminine", "🫒", "Nous goûtons une olive verte.", "We taste a green olive."],
  ["occ-partager", "occitanie", 3, "partager", "partager", "to share", "/paʁtaʒe/", "verb", null, "🤲", "Ils aiment partager un repas sur la terrasse.", "They like sharing a meal on the terrace."],
  ["occ-convivial", "occitanie", 3, "convivial", "convivial", "friendly / sociable", "/kɔ̃vivjal/", "adjective", null, "😊", "L'ambiance du café est conviviale.", "The café atmosphere is friendly."],

  // Provence-Alpes-Côte d'Azur — lessons 2 and 3
  ["paca-marche-provencal", "provence-alpes-cote-d-azur", 2, "un marché provençal", "marche provencal", "a Provençal market", "/œ̃ maʁʃe pʁɔvɑ̃sal/", "noun", "masculine", "🧺", "Le marché provençal ouvre sur la place.", "The Provençal market opens on the square."],
  ["paca-huile-olive", "provence-alpes-cote-d-azur", 2, "l'huile d'olive", "huile d olive", "olive oil", "/lɥil dɔliv/", "noun", "feminine", "🫒", "Cette huile d'olive a un goût fruité.", "This olive oil has a fruity taste."],
  ["paca-tomate", "provence-alpes-cote-d-azur", 2, "une tomate", "tomate", "a tomato", "/yn tɔmat/", "noun", "feminine", "🍅", "Je choisis une tomate bien mûre.", "I choose a nicely ripe tomato."],
  ["paca-sentir", "provence-alpes-cote-d-azur", 2, "sentir", "sentir", "to smell / feel", "/sɑ̃tiʁ/", "verb", null, "👃", "On peut sentir la lavande dans l'air.", "You can smell lavender in the air."],
  ["paca-parfume", "provence-alpes-cote-d-azur", 2, "parfumé", "parfume", "fragrant / flavoured", "/paʁfyme/", "adjective", null, "🌿", "Le miel est parfumé aux herbes de Provence.", "The honey is fragrant with Provençal herbs."],
  ["paca-port-plaisance", "provence-alpes-cote-d-azur", 3, "un port de plaisance", "port de plaisance", "a marina", "/œ̃ pɔʁ də plɛzɑ̃s/", "noun", "masculine", "⛵", "Le port de plaisance accueille de petits voiliers.", "The marina welcomes small sailing boats."],
  ["paca-parasol", "provence-alpes-cote-d-azur", 3, "un parasol", "parasol", "a sun umbrella", "/œ̃ paʁasɔl/", "noun", "masculine", "⛱️", "Nous installons le parasol près de l'eau.", "We put up the sun umbrella near the water."],
  ["paca-rocher", "provence-alpes-cote-d-azur", 3, "un rocher", "rocher", "a rock", "/œ̃ ʁɔʃe/", "noun", "masculine", "🪨", "Un sentier descend entre les rochers.", "A path descends between the rocks."],
  ["paca-plonger", "provence-alpes-cote-d-azur", 3, "plonger", "plonger", "to dive", "/plɔ̃ʒe/", "verb", null, "🤿", "Ils vont plonger dans une eau claire.", "They are going to dive into clear water."],
  ["paca-turquoise", "provence-alpes-cote-d-azur", 3, "turquoise", "turquoise", "turquoise", "/tyʁkwaz/", "adjective", null, "🩵", "La mer est turquoise au fond de la calanque.", "The sea is turquoise at the end of the cove."],

  // Corse — lessons 2 and 3
  ["cor-charcuterie", "corse", 2, "la charcuterie", "charcuterie", "cured meats", "/la ʃaʁkytʁi/", "noun", "feminine", "🥓", "La charcuterie est servie avec du pain.", "The cured meats are served with bread."],
  ["cor-chataigne", "corse", 2, "une châtaigne", "chataigne", "a chestnut", "/yn ʃatɛɲ/", "noun", "feminine", "🌰", "Les châtaignes tombent au début de l'automne.", "Chestnuts fall at the beginning of autumn."],
  ["cor-fontaine", "corse", 2, "une fontaine", "fontaine", "a fountain", "/yn fɔ̃tɛn/", "noun", "feminine", "⛲", "Une fontaine coule au centre du village.", "A fountain flows in the centre of the village."],
  ["cor-preparer", "corse", 2, "préparer", "preparer", "to prepare", "/pʁepaʁe/", "verb", null, "👩‍🍳", "Nous préparons un repas avec des produits corses.", "We prepare a meal with Corsican products."],
  ["cor-typique", "corse", 2, "typique", "typique", "typical", "/tipik/", "adjective", null, "🏡", "Cette maison en pierre est typique du village.", "This stone house is typical of the village."],
  ["cor-crique", "corse", 3, "une crique", "crique", "a small cove", "/yn kʁik/", "noun", "feminine", "🏝️", "Le sentier descend vers une crique tranquille.", "The path descends towards a quiet cove."],
  ["cor-col", "corse", 3, "un col", "col", "a mountain pass", "/œ̃ kɔl/", "noun", "masculine", "⛰️", "Le col offre une vue sur les deux côtes.", "The mountain pass offers a view of both coasts."],
  ["cor-sac-dos", "corse", 3, "un sac à dos", "sac a dos", "a backpack", "/œ̃ sak a do/", "noun", "masculine", "🎒", "Mon sac à dos contient de l'eau et une carte.", "My backpack contains water and a map."],
  ["cor-monter", "corse", 3, "monter", "monter", "to climb / go up", "/mɔ̃te/", "verb", null, "⬆️", "Nous montons jusqu'au village à pied.", "We walk up to the village."],
  ["cor-isole", "corse", 3, "isolé", "isole", "remote / isolated", "/izɔle/", "adjective", null, "🗺️", "La plage est belle mais isolée.", "The beach is beautiful but remote."],

  // Guadeloupe — lessons 2 and 3
  ["gua-marche-epices", "guadeloupe", 2, "un marché aux épices", "marche aux epices", "a spice market", "/œ̃ maʁʃe oz epis/", "noun", "masculine", "🌶️", "Le marché aux épices est plein de couleurs.", "The spice market is full of colours."],
  ["gua-banane", "guadeloupe", 2, "une banane", "banane", "a banana", "/yn banan/", "noun", "feminine", "🍌", "Elle coupe une banane pour le dessert.", "She slices a banana for dessert."],
  ["gua-plage-sable-noir", "guadeloupe", 2, "une plage de sable noir", "plage de sable noir", "a black-sand beach", "/yn plaʒ də sabl nwaʁ/", "noun", "feminine", "🏖️", "Nous découvrons une plage de sable noir.", "We discover a black-sand beach."],
  ["gua-nager", "guadeloupe", 2, "nager", "nager", "to swim", "/naʒe/", "verb", null, "🏊", "Les enfants aiment nager dans l'eau calme.", "The children like swimming in the calm water."],
  ["gua-sucre", "guadeloupe", 2, "sucré", "sucre", "sweet", "/sykʁe/", "adjective", null, "🍬", "Ce fruit est parfumé et sucré.", "This fruit is fragrant and sweet."],
  ["gua-averse-tropicale", "guadeloupe", 3, "une averse tropicale", "averse tropicale", "a tropical shower", "/yn avɛʁs tʁɔpikal/", "noun", "feminine", "🌧️", "Une averse tropicale passe rapidement.", "A tropical shower passes quickly."],
  ["gua-foret-humide", "guadeloupe", 3, "une forêt humide", "foret humide", "a rainforest", "/yn fɔʁɛ ymid/", "noun", "feminine", "🌴", "La forêt humide abrite de nombreuses plantes.", "The rainforest is home to many plants."],
  ["gua-source", "guadeloupe", 3, "une source", "source", "a spring", "/yn suʁs/", "noun", "feminine", "💦", "Une source claire traverse les rochers.", "A clear spring runs through the rocks."],
  ["gua-se-proteger", "guadeloupe", 3, "se protéger", "se proteger", "to protect oneself", "/sə pʁɔteʒe/", "pronominal verb", null, "☔", "Il faut se protéger du soleil à midi.", "You must protect yourself from the midday sun."],
  ["gua-rafraichissant", "guadeloupe", 3, "rafraîchissant", "rafraichissant", "refreshing", "/ʁafʁɛʃisɑ̃/", "adjective", null, "🧊", "L'eau de la cascade est rafraîchissante.", "The waterfall water is refreshing."],

  // Martinique — lessons 2 and 3
  ["mar-ananas", "martinique", 2, "un ananas", "ananas", "a pineapple", "/œ̃n anana/", "noun", "masculine", "🍍", "Cet ananas vient du marché local.", "This pineapple comes from the local market."],
  ["mar-epice", "martinique", 2, "une épice", "epice", "a spice", "/yn epis/", "noun", "feminine", "🌶️", "Cette épice donne du parfum au plat.", "This spice adds flavour to the dish."],
  ["mar-marche-local", "martinique", 2, "un marché local", "marche local", "a local market", "/œ̃ maʁʃe lɔkal/", "noun", "masculine", "🧺", "Nous achetons des fruits au marché local.", "We buy fruit at the local market."],
  ["mar-cuisiner", "martinique", 2, "cuisiner", "cuisiner", "to cook", "/kɥizine/", "verb", null, "🍳", "Elle aime cuisiner avec des herbes fraîches.", "She likes cooking with fresh herbs."],
  ["mar-doux", "martinique", 2, "doux", "doux", "sweet / mild", "/du/", "adjective", null, "🍯", "La chair de ce fruit est douce.", "The flesh of this fruit is sweet."],
  ["mar-montagne-pelee", "martinique", 3, "la montagne Pelée", "montagne pelee", "Mount Pelée", "/la mɔ̃taɲ pəle/", "noun", "feminine", "🌋", "La montagne Pelée domine le nord de l'île.", "Mount Pelée overlooks the north of the island."],
  ["mar-baie", "martinique", 3, "une baie", "baie", "a bay", "/yn bɛ/", "noun", "feminine", "🌊", "La yole traverse la baie au lever du jour.", "The yole crosses the bay at sunrise."],
  ["mar-sable-noir", "martinique", 3, "le sable noir", "sable noir", "black sand", "/lə sabl nwaʁ/", "noun", "masculine", "⬛", "Le sable noir chauffe vite au soleil.", "The black sand heats up quickly in the sun."],
  ["mar-explorer", "martinique", 3, "explorer", "explorer", "to explore", "/ɛksplɔʁe/", "verb", null, "🧭", "Nous partons explorer la côte nord.", "We are setting out to explore the north coast."],
  ["mar-calme", "martinique", 3, "calme", "calme", "calm", "/kalm/", "adjective", null, "😌", "La mer est calme dans la baie.", "The sea is calm in the bay."],

  // Guyane — lessons 2 and 3
  ["guy-pirogue", "guyane", 2, "une pirogue", "pirogue", "a dugout canoe", "/yn piʁɔɡ/", "noun", "feminine", "🛶", "La pirogue avance au milieu du fleuve.", "The dugout canoe moves along the middle of the river."],
  ["guy-rive", "guyane", 2, "une rive", "rive", "a riverbank", "/yn ʁiv/", "noun", "feminine", "🏞️", "De grands arbres poussent sur chaque rive.", "Tall trees grow on each riverbank."],
  ["guy-village-riverain", "guyane", 2, "un village riverain", "village riverain", "a riverside village", "/œ̃ vilaʒ ʁivʁɛ̃/", "noun", "masculine", "🏘️", "Nous faisons halte dans un village riverain.", "We stop in a riverside village."],
  ["guy-remonter", "guyane", 2, "remonter", "remonter", "to travel upstream", "/ʁəmɔ̃te/", "verb", null, "⬆️", "Ils vont remonter le fleuve en pirogue.", "They are going to travel upstream by canoe."],
  ["guy-lointain", "guyane", 2, "lointain", "lointain", "distant / remote", "/lwɛ̃tɛ̃/", "adjective", null, "🌅", "Le village paraît encore lointain.", "The village still seems far away."],
  ["guy-paresseux", "guyane", 3, "un paresseux", "paresseux", "a sloth", "/œ̃ paʁɛsø/", "noun", "masculine", "🦥", "Un paresseux dort dans les branches.", "A sloth sleeps in the branches."],
  ["guy-toucan", "guyane", 3, "un toucan", "toucan", "a toucan", "/œ̃ tukɑ̃/", "noun", "masculine", "🦜", "Nous apercevons un toucan au-dessus du sentier.", "We spot a toucan above the path."],
  ["guy-saison-pluies", "guyane", 3, "la saison des pluies", "saison des pluies", "the rainy season", "/la sɛzɔ̃ de plɥi/", "noun", "feminine", "🌧️", "La saison des pluies commence bientôt.", "The rainy season begins soon."],
  ["guy-apercevoir", "guyane", 3, "apercevoir", "apercevoir", "to catch sight of", "/apɛʁsəvwaʁ/", "verb", null, "👀", "On peut apercevoir des singes au matin.", "You can catch sight of monkeys in the morning."],
  ["guy-tropical", "guyane", 3, "tropical", "tropical", "tropical", "/tʁɔpikal/", "adjective", null, "🌴", "Le climat tropical est chaud et humide.", "The tropical climate is hot and humid."],

  // La Réunion — lessons 2 and 3
  ["reu-belvedere", "la-reunion", 2, "un belvédère", "belvedere", "a viewpoint", "/œ̃ bɛlvedɛʁ/", "noun", "masculine", "🔭", "Le belvédère donne sur tout le cirque.", "The viewpoint overlooks the entire cirque."],
  ["reu-ravine", "la-reunion", 2, "une ravine", "ravine", "a ravine", "/yn ʁavin/", "noun", "feminine", "⛰️", "Une passerelle franchit la ravine.", "A footbridge crosses the ravine."],
  ["reu-sentier", "la-reunion", 2, "un sentier", "sentier", "a trail", "/œ̃ sɑ̃tje/", "noun", "masculine", "🥾", "Le sentier monte entre les fougères.", "The trail climbs between the ferns."],
  ["reu-descendre", "la-reunion", 2, "descendre", "descendre", "to go down / descend", "/desɑ̃dʁ/", "verb", null, "⬇️", "Nous descendons vers le village avant la pluie.", "We go down towards the village before the rain."],
  ["reu-vertigineux", "la-reunion", 2, "vertigineux", "vertigineux", "dizzyingly steep", "/vɛʁtiʒinø/", "adjective", null, "😮", "Le panorama depuis la crête est vertigineux.", "The view from the ridge is dizzying."],
  ["reu-cari", "la-reunion", 3, "le cari", "cari", "Réunion-style curry", "/lə kaʁi/", "noun", "masculine", "🍛", "Le cari mijote doucement dans la marmite.", "The cari simmers gently in the cooking pot."],
  ["reu-vanille", "la-reunion", 3, "la vanille", "vanille", "vanilla", "/la vanij/", "noun", "feminine", "🌱", "La vanille parfume le dessert.", "The vanilla flavours the dessert."],
  ["reu-alize", "la-reunion", 3, "un alizé", "alize", "a trade wind", "/œ̃n alize/", "noun", "masculine", "💨", "Un alizé rafraîchit la côte est.", "A trade wind cools the east coast."],
  ["reu-mijoter", "la-reunion", 3, "mijoter", "mijoter", "to simmer", "/miʒɔte/", "verb", null, "🥘", "Il faut laisser mijoter la sauce.", "You need to let the sauce simmer."],
  ["reu-intense", "la-reunion", 3, "intense", "intense", "intense", "/ɛ̃tɑ̃s/", "adjective", null, "🌋", "La chaleur près du volcan est intense.", "The heat near the volcano is intense."],

  // Mayotte — lessons 2 and 3
  ["may-village-cotier", "mayotte", 2, "un village côtier", "village cotier", "a coastal village", "/œ̃ vilaʒ kotje/", "noun", "masculine", "🏘️", "Le village côtier s'éveille tôt le matin.", "The coastal village wakes early in the morning."],
  ["may-pirogue-balancier", "mayotte", 2, "une pirogue à balancier", "pirogue a balancier", "an outrigger canoe", "/yn piʁɔɡ a balɑ̃sje/", "noun", "feminine", "🛶", "La pirogue à balancier glisse sur le lagon.", "The outrigger canoe glides across the lagoon."],
  ["may-fruit-tropical", "mayotte", 2, "un fruit tropical", "fruit tropical", "a tropical fruit", "/œ̃ fʁɥi tʁɔpikal/", "noun", "masculine", "🥭", "Le vendeur coupe un fruit tropical bien mûr.", "The vendor slices a ripe tropical fruit."],
  ["may-discuter", "mayotte", 2, "discuter", "discuter", "to chat / discuss", "/diskyte/", "verb", null, "💬", "Les voisins discutent devant la maison.", "The neighbours chat in front of the house."],
  ["may-multilingue", "mayotte", 2, "multilingue", "multilingue", "multilingual", "/myltilɛ̃ɡ/", "adjective", null, "🗣️", "La vie quotidienne est profondément multilingue.", "Daily life is deeply multilingual."],
  ["may-recif", "mayotte", 3, "un récif", "recif", "a reef", "/œ̃ ʁesif/", "noun", "masculine", "🪸", "Le récif abrite de petits poissons colorés.", "The reef shelters small colourful fish."],
  ["may-maree-basse", "mayotte", 3, "la marée basse", "maree basse", "low tide", "/la maʁe bas/", "noun", "feminine", "🌊", "À marée basse, le récif devient visible.", "At low tide, the reef becomes visible."],
  ["may-dechets", "mayotte", 3, "les déchets", "dechets", "waste / litter", "/le deʃɛ/", "noun", "masculine", "♻️", "Nous ramassons les déchets sur la plage.", "We pick up litter on the beach."],
  ["may-proteger", "mayotte", 3, "protéger", "proteger", "to protect", "/pʁɔteʒe/", "verb", null, "🛡️", "Il faut protéger les tortues et leurs nids.", "We must protect the turtles and their nests."],
  ["may-fragile", "mayotte", 3, "fragile", "fragile", "fragile", "/fʁaʒil/", "adjective", null, "🤲", "Cet écosystème marin est très fragile.", "This marine ecosystem is very fragile."],
] as const satisfies readonly CurriculumEntry[];

const foundationWordsWithMetadata: Word[] = FOUNDATION_WORDS.map((word) => {
  const plan = [...CURRICULUM_PLAN[word.regionId]].sort(
    (first, second) => first.lesson - second.lesson,
  )[0];
  if (!plan) {
    throw new Error(`Missing curriculum plan for ${word.regionId}.`);
  }
  return {
    ...word,
    lesson: plan.lesson,
    cefr: plan.cefr,
    topic: plan.topic,
  };
});

const expansionWordsWithMetadata: Word[] = CURRICULUM_EXPANSION.map(
  ([id, regionId, lesson, french, search, english, ipa, partOfSpeech, gender, emoji, exampleFr, exampleEn]) => {
    const plan = CURRICULUM_PLAN[regionId].find(
      (candidate) => candidate.lesson === lesson,
    );
    if (!plan) {
      throw new Error(`Missing curriculum plan for ${regionId} lesson ${lesson}.`);
    }
    return { id, regionId, lesson, french, search, english, ipa, partOfSpeech, gender, emoji, exampleFr, exampleEn, cefr: plan.cefr, topic: plan.topic };
  },
);

export const WORDS = [
  ...foundationWordsWithMetadata,
  ...expansionWordsWithMetadata,
] as const satisfies readonly Word[];

export const MASTERY_STAGE_LABELS = [
  "Nouveau",
  "Découverte",
  "En pratique",
  "Familier",
  "Solide",
  "Maîtrisé",
  "Acquis",
] as const;

export type CollectibleRarity =
  | "common"
  | "uncommon"
  | "rare"
  | "epic"
  | "legendary";

export type Collectible = {
  id: string;
  name: string;
  emoji: string;
  rarity: CollectibleRarity;
  description: string;
  unlockAtXp: number;
};

export const SEED_COLLECTIBLES = [
  {
    id: "metro-ticket",
    name: "Metro Ticket",
    emoji: "🎟️",
    rarity: "common",
    description: "Your first souvenir from the capital.",
    unlockAtXp: 100,
  },
  {
    id: "lighthouse-pin",
    name: "Lighthouse Pin",
    emoji: "🗼",
    rarity: "uncommon",
    description: "A bright marker from the Atlantic coast.",
    unlockAtXp: 400,
  },
  {
    id: "castle-key",
    name: "Castle Key",
    emoji: "🗝️",
    rarity: "rare",
    description: "A key said to open a Loire Valley gate.",
    unlockAtXp: 900,
  },
  {
    id: "alpine-badge",
    name: "Alpine Badge",
    emoji: "🏔️",
    rarity: "epic",
    description: "Earned after climbing through a difficult review set.",
    unlockAtXp: 1600,
  },
  {
    id: "golden-compass",
    name: "Golden Compass",
    emoji: "🧭",
    rarity: "legendary",
    description: "For travellers who keep finding their way back to French.",
    unlockAtXp: 3000,
  },
] as const satisfies readonly Collectible[];

export const regions = REGIONS;
export const words = WORDS;
